import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
const base=z.object({diaSemana:z.number().int().min(0).max(6),horario:z.string().regex(/^\d{2}:\d{2}$/),descricao:z.string().trim().min(3).max(80)});const editar=base.extend({id:z.uuid(),ativo:z.boolean()});
const permitidos=["admin_plataforma","admin_paroquia","atendente_secretaria"];
const map=(i:Record<string,unknown>)=>({id:i.id,diaSemana:Number(i.dia_semana),horario:String(i.horario).slice(0,5),descricao:i.descricao,ativo:i.ativo});
function erro(e:unknown){const m=e instanceof Error?e.message:e&&typeof e==="object"&&"message" in e?String(e.message):"Erro interno.";return NextResponse.json({erro:/duplicate|unique/i.test(m)?"Já existe uma celebração nesse dia e horário.":m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:400});}
export async function GET(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_horarios_celebracoes").select("*").eq("paroquia_id",paroquiaId).order("dia_semana").order("horario");if(error)throw error;return NextResponse.json((data??[]).map(i=>map(i)));}catch(e){return erro(e)}}
export async function POST(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!["admin_plataforma","admin_paroquia"].includes(u.role))throw new Error("FORBIDDEN");const d=base.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_horarios_celebracoes").insert({paroquia_id:paroquiaId,dia_semana:d.diaSemana,horario:d.horario,descricao:d.descricao}).select("*").single();if(error)throw error;return NextResponse.json(map(data),{status:201});}catch(e){return erro(e)}}
export async function PATCH(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!["admin_plataforma","admin_paroquia"].includes(u.role))throw new Error("FORBIDDEN");const d=editar.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_horarios_celebracoes").update({dia_semana:d.diaSemana,horario:d.horario,descricao:d.descricao,ativo:d.ativo,updated_at:new Date().toISOString()}).eq("id",d.id).eq("paroquia_id",paroquiaId).select("*").single();if(error)throw error;return NextResponse.json(map(data));}catch(e){return erro(e)}}
