"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { CalendarPlus,ChevronLeft,ChevronRight,Pencil } from "lucide-react";
import toast from "react-hot-toast";
import { ProtectedArea } from "@/components/auth/ProtectedArea";
import { ModuleHeader } from "@/components/layout/ModuleHeader";
import { obterTokenAcesso } from "@/lib/auth/client-session";
type Evento={id:string;titulo:string;tipo:string;inicio:string;fim:string;local:string;responsavel:string;observacoes:string;status:string;criadoPorNome:string};
const tipos:Record<string,string>={BATISMO:"Batismo",CASAMENTO:"Casamento",CURSO:"Curso",REUNIAO:"Reunião",CELEBRACAO:"Celebração",ATENDIMENTO:"Atendimento",OUTRO:"Outro"};const cores:Record<string,string>={BATISMO:"bg-sky-100 text-sky-800",CASAMENTO:"bg-pink-100 text-pink-800",CURSO:"bg-amber-100 text-amber-800",REUNIAO:"bg-purple-100 text-purple-800",CELEBRACAO:"bg-emerald-100 text-emerald-800",ATENDIMENTO:"bg-blue-100 text-blue-800",OUTRO:"bg-slate-200 text-slate-800"};
const localInput=(d:Date)=>{const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)};const inicioPadrao=()=>{const d=new Date();d.setMinutes(0,0,0);d.setHours(d.getHours()+1);return d};const vazio=()=>{const i=inicioPadrao(),f=new Date(i.getTime()+3600000);return{id:"",titulo:"",tipo:"CELEBRACAO",inicio:localInput(i),fim:localInput(f),local:"",responsavel:"",observacoes:"",status:"AGENDADO"}};
async function requisicao<T>(url:string,init?:RequestInit){const token=await obterTokenAcesso();const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok){const e=new Error(d.erro||"Operação não concluída.") as Error&{status?:number};e.status=r.status;throw e;}return d as T;}
function Conteudo(){const[visao,setVisao]=useState<"DIA"|"SEMANA"|"MES"|"LISTA">("MES");const[referencia,setReferencia]=useState(new Date());const[eventosCarregados,setEventos]=useState<Evento[]>([]);const[busca,setBusca]=useState("");const[form,setForm]=useState(vazio);const[aberto,setAberto]=useState(false);const[salvando,setSalvando]=useState(false);
  const periodo=useMemo(()=>{const base=new Date(referencia);base.setHours(0,0,0,0);if(visao==="LISTA"){const hoje=new Date();hoje.setHours(0,0,0,0);return{inicio:hoje,fim:new Date(hoje.getFullYear(),hoje.getMonth()+6,hoje.getDate())}}if(visao==="DIA")return{inicio:base,fim:new Date(base.getTime()+86400000)};if(visao==="SEMANA"){base.setDate(base.getDate()-base.getDay());return{inicio:base,fim:new Date(base.getTime()+7*86400000)}}const i=new Date(base.getFullYear(),base.getMonth(),1);return{inicio:i,fim:new Date(base.getFullYear(),base.getMonth()+1,1)}},[referencia,visao]);
  const carregar=useCallback(async()=>{try{const p=new URLSearchParams({inicio:periodo.inicio.toISOString(),fim:periodo.fim.toISOString()});setEventos(await requisicao<Evento[]>(`/api/secretaria/agenda?${p}`));}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível carregar a agenda.");}},[periodo]);useEffect(()=>{void carregar();},[carregar]);
  function mover(n:number){const d=new Date(referencia);if(visao==="MES")d.setMonth(d.getMonth()+n);else d.setDate(d.getDate()+n*(visao==="SEMANA"?7:1));setReferencia(d)}
  function novo(data?:Date){const f=vazio();if(data){const i=new Date(data);i.setHours(9,0,0,0);f.inicio=localInput(i);f.fim=localInput(new Date(i.getTime()+3600000));}setForm(f);setAberto(true)}function editar(e:Evento){setForm({id:e.id,titulo:e.titulo,tipo:e.tipo,inicio:localInput(new Date(e.inicio)),fim:localInput(new Date(e.fim)),local:e.local,responsavel:e.responsavel,observacoes:e.observacoes,status:e.status});setAberto(true)}
  async function salvar(e:FormEvent,ignorarConflito=false){e.preventDefault();setSalvando(true);try{const body={...form,inicio:new Date(form.inicio).toISOString(),fim:new Date(form.fim).toISOString(),ignorarConflito};await requisicao("/api/secretaria/agenda",{method:form.id?"PATCH":"POST",body:JSON.stringify(body)});toast.success("Compromisso salvo.");setAberto(false);await carregar();}catch(e){const erro=e as Error&{status?:number};if(erro.status===409&&window.confirm(`${erro.message}\n\nDeseja salvar mesmo assim?`)){setSalvando(false);return void salvar({preventDefault:()=>undefined} as FormEvent,true);}toast.error(erro.message);}finally{setSalvando(false)}}
  const titulo=visao==="LISTA"?"Próximos seis meses":visao==="MES"?referencia.toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):visao==="SEMANA"?`${periodo.inicio.toLocaleDateString("pt-BR")} a ${new Date(periodo.fim.getTime()-86400000).toLocaleDateString("pt-BR")}`:referencia.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});const diasMes=useMemo(()=>{if(visao!=="MES")return[];const primeiro=new Date(referencia.getFullYear(),referencia.getMonth(),1);const inicio=new Date(primeiro);inicio.setDate(1-primeiro.getDay());return Array.from({length:42},(_,i)=>new Date(inicio.getFullYear(),inicio.getMonth(),inicio.getDate()+i));},[referencia,visao]);const eventos=eventosCarregados.filter(e=>visao!=="LISTA"||!busca||`${e.titulo} ${tipos[e.tipo]} ${e.local} ${e.responsavel}`.toLowerCase().includes(busca.toLowerCase()));
  return <main className="min-h-screen bg-slate-100"><ModuleHeader titulo="Agenda paroquial"/><div className="mx-auto max-w-7xl space-y-4 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><button onClick={()=>mover(-1)} className="rounded-xl border p-3"><ChevronLeft/></button><button onClick={()=>setReferencia(new Date())} className="rounded-xl border px-4 py-3 font-bold">Hoje</button><button onClick={()=>mover(1)} className="rounded-xl border p-3"><ChevronRight/></button></div><h2 className="text-lg font-black capitalize">{titulo}</h2><div className="flex flex-wrap gap-2"><div className="flex flex-wrap rounded-xl border p-1">{(["DIA","SEMANA","MES","LISTA"] as const).map(v=><button key={v} onClick={()=>setVisao(v)} className={`rounded-lg px-3 py-2 text-sm font-bold ${visao===v?"bg-blue-600 text-white":""}`}>{v==="MES"?"Mês":v==="DIA"?"Dia":v==="SEMANA"?"Semana":"Próximos"}</button>)}</div><button onClick={()=>novo()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-black text-white"><CalendarPlus size={18}/>Novo</button></div></div>
    {visao==="LISTA"&&<input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar por nome, tipo, local ou responsável" className="min-h-12 w-full rounded-xl border bg-white px-4 shadow-sm"/>}
    {visao==="MES"?<section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid grid-cols-7 bg-slate-100 text-center text-xs font-bold uppercase text-slate-500">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(d=><div key={d} className="p-2">{d}</div>)}</div><div className="grid grid-cols-7">{diasMes.map(d=>{const doDia=eventos.filter(e=>new Date(e.inicio).toDateString()===d.toDateString());return <button key={d.toISOString()} onClick={()=>novo(d)} className={`min-h-24 border-b border-r p-1 text-left align-top sm:min-h-32 sm:p-2 ${d.getMonth()!==referencia.getMonth()?"bg-slate-50 text-slate-400":""}`}><span className="text-xs font-bold">{d.getDate()}</span><div className="mt-1 space-y-1">{doDia.slice(0,3).map(e=><span key={e.id} onClick={x=>{x.stopPropagation();editar(e)}} className={`block truncate rounded px-1 py-1 text-[10px] font-bold sm:text-xs ${cores[e.tipo]}`}>{new Date(e.inicio).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})} {e.titulo}</span>)}{doDia.length>3&&<span className="text-xs font-bold text-blue-600">+{doDia.length-3}</span>}</div></button>})}</div></section>:<section className="space-y-2">{eventos.map(e=><article key={e.id} className="flex items-start justify-between gap-3 rounded-2xl border bg-white p-4 shadow-sm"><div><span className={`rounded-full px-2 py-1 text-xs font-bold ${cores[e.tipo]}`}>{tipos[e.tipo]}</span><h3 className="mt-2 font-black">{e.titulo}</h3><p className="text-sm text-slate-600">{new Date(e.inicio).toLocaleString("pt-BR")} até {new Date(e.fim).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}{e.local&&` • ${e.local}`}</p>{e.responsavel&&<p className="text-sm text-slate-500">Responsável: {e.responsavel}</p>}</div><button onClick={()=>editar(e)} className="rounded-xl border p-3 text-blue-700"><Pencil size={18}/></button></article>)}{!eventos.length&&<div className="rounded-2xl bg-white p-10 text-center text-slate-500">Nenhum compromisso neste período.</div>}</section>}
  </div>{aberto&&<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/50 sm:place-items-center"><form onSubmit={e=>void salvar(e)} className="max-h-[95vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-xl sm:rounded-3xl"><h2 className="text-xl font-black">{form.id?"Editar compromisso":"Novo compromisso"}</h2><div className="mt-4 space-y-3"><label className="block text-sm font-bold">Título<input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-3 font-normal" required/></label><div className="grid grid-cols-2 gap-2"><label className="text-sm font-bold">Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border bg-white px-3">{Object.entries(tipos).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-bold">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border bg-white px-3"><option value="AGENDADO">Agendado</option><option value="CONFIRMADO">Confirmado</option><option value="CONCLUIDO">Concluído</option><option value="CANCELADO">Cancelado</option></select></label></div><div className="grid grid-cols-2 gap-2"><label className="text-sm font-bold">Início<input type="datetime-local" value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-2" required/></label><label className="text-sm font-bold">Término<input type="datetime-local" value={form.fim} onChange={e=>setForm({...form,fim:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-2" required/></label></div><label className="block text-sm font-bold">Local<input value={form.local} onChange={e=>setForm({...form,local:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-3 font-normal"/></label><label className="block text-sm font-bold">Responsável<input value={form.responsavel} onChange={e=>setForm({...form,responsavel:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-3 font-normal"/></label><label className="block text-sm font-bold">Observações<textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal"/></label></div><div className="mt-5 flex gap-2"><button disabled={salvando} className="min-h-12 flex-1 rounded-xl bg-blue-600 font-black text-white">{salvando?"Salvando...":"Salvar"}</button><button type="button" onClick={()=>setAberto(false)} className="rounded-xl border px-5 font-bold">Cancelar</button></div></form></div>}</main>}
export default function AgendaPage(){return <ProtectedArea><Conteudo/></ProtectedArea>}
