import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
type Contexto={params:Promise<{id:string}>};
const schema=z.object({documentos:z.array(z.object({id:z.string(),nome:z.string().trim().min(2),entregue:z.boolean()})).max(30)});
const permitidos=["admin_plataforma","admin_paroquia","atendente_secretaria"];
function erro(e:unknown){const m=e instanceof Error?e.message:e&&typeof e==="object"&&"message" in e?String(e.message):"Erro interno.";return NextResponse.json({erro:m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:400});}
export async function GET(req:NextRequest,ctx:Contexto){try{const usuario=await exigirUsuarioAtivo(req);if(!permitidos.includes(usuario.role))throw new Error("FORBIDDEN");const{supabase,paroquiaId,paroquia}=await resolverParoquiaDaRequisicao(req,usuario);const id=(await ctx.params).id;const[solicitacao,historico]=await Promise.all([supabase.from("secretaria_solicitacoes").select("*").eq("id",id).eq("paroquia_id",paroquiaId).single(),supabase.from("secretaria_solicitacoes_historico").select("id,status,observacao,criado_por_nome,created_at").eq("solicitacao_id",id).eq("paroquia_id",paroquiaId).order("created_at",{ascending:false})]);if(solicitacao.error)throw solicitacao.error;if(historico.error)throw historico.error;const i=solicitacao.data;return NextResponse.json({paroquia:{nome:paroquia.nome},solicitacao:{id:i.id,protocolo:i.protocolo,tipo:i.tipo,servicoNome:i.servico_nome||i.tipo,solicitanteNome:i.solicitante_nome,telefone:i.telefone,interessadoNome:i.interessado_nome,prazo:i.prazo,observacoes:i.observacoes,status:i.status,valor:Number(i.valor),pago:i.pago,pagoEm:i.pago_em,criadoPorNome:i.criado_por_nome,createdAt:i.created_at,documentosChecklist:i.documentos_checklist??[]},historico:(historico.data??[]).map(h=>({id:h.id,status:h.status,observacao:h.observacao,criadoPorNome:h.criado_por_nome,createdAt:h.created_at}))});}catch(e){return erro(e)}}
export async function PATCH(req:NextRequest,ctx:Contexto){try{const usuario=await exigirUsuarioAtivo(req);if(!permitidos.includes(usuario.role))throw new Error("FORBIDDEN");const d=schema.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,usuario);const id=(await ctx.params).id;const atualizacao=await supabase.from("secretaria_solicitacoes").update({documentos_checklist:d.documentos,updated_at:new Date().toISOString()}).eq("id",id).eq("paroquia_id",paroquiaId).select("id").single();if(atualizacao.error)throw atualizacao.error;return NextResponse.json({id});}catch(e){return erro(e)}}
