"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { HeartHandshake, ShieldCheck } from "lucide-react";
import { roleLabels, Role } from "@/config/roles";
import { maskTelefone } from "@/lib/formatters/masks";

type Detalhe = { paroquiaNome: string; role: Role; expiresAt: string };

export default function ConvitePage() {
  const params = useSearchParams(); const router = useRouter(); const token = params.get("token") || "";
  const [detalhe, setDetalhe] = useState<Detalhe | null>(null); const [erro, setErro] = useState(""); const [salvando, setSalvando] = useState(false);
  const [form, setForm] = useState({ nome: "", email: "", telefone: "", senha: "", confirmacao: "" });
  useEffect(() => { if (!token) { setErro("Convite inválido."); return; } fetch(`/api/convites-usuarios/aceitar?token=${encodeURIComponent(token)}`).then(async (r) => { const dados = await r.json(); if (!r.ok) throw new Error(dados.erro); setDetalhe(dados); }).catch((e) => setErro(e instanceof Error ? e.message : "Não foi possível validar o convite.")); }, [token]);
  async function salvar(event: FormEvent) { event.preventDefault(); if (form.senha !== form.confirmacao) return toast.error("As senhas não coincidem."); setSalvando(true); try { const resposta = await fetch("/api/convites-usuarios/aceitar", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, nome: form.nome, email: form.email, telefone: form.telefone, senha: form.senha }) }); const dados = await resposta.json(); if (!resposta.ok) throw new Error(dados.erro); toast.success("Cadastro concluído. Você já pode entrar."); router.replace("/login"); } catch (e) { toast.error(e instanceof Error ? e.message : "Não foi possível concluir o cadastro."); } finally { setSalvando(false); } }
  return <main className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-slate-100 p-5 sm:p-10"><section className="mx-auto max-w-xl rounded-3xl border bg-white p-6 shadow-xl shadow-blue-950/10 sm:p-10"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-100 text-blue-700"><HeartHandshake /></span><div><p className="text-xs font-black tracking-[.16em] text-blue-700">CONVITE ÁGAPE SOCIAL</p><h1 className="mt-1 text-2xl font-black tracking-tight">Conclua seu cadastro</h1></div></div>{erro ? <p className="mt-7 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{erro}</p> : !detalhe ? <p className="mt-7 text-sm text-slate-500">Validando convite...</p> : <><div className="mt-7 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-950"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-blue-700" size={20}/><p>Você foi convidado para <strong>{detalhe.paroquiaNome}</strong> como <strong>{roleLabels[detalhe.role]}</strong>.</p></div></div><form onSubmit={salvar} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Nome completo<input required value={form.nome} onChange={(e)=>setForm({...form,nome:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-semibold">E-mail<input required type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-semibold">Telefone<input value={form.telefone} onChange={(e)=>setForm({...form,telefone:maskTelefone(e.target.value)})} maxLength={15} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" placeholder="(11) 99999-9999" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Senha<input required type="password" minLength={8} value={form.senha} onChange={(e)=>setForm({...form,senha:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-semibold">Confirmar senha<input required type="password" minLength={8} value={form.confirmacao} onChange={(e)=>setForm({...form,confirmacao:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label></div><button disabled={salvando} className="w-full rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-60">{salvando ? "Concluindo..." : "Criar acesso"}</button></form><p className="mt-4 text-center text-xs text-slate-500">Este convite é individual, possui validade e só pode ser utilizado uma vez.</p></>}</section></main>;
}
