import { randomUUID } from "node:crypto";
import { NextRequest,NextResponse } from "next/server";
import { exigirAdministrador } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";

const tabelasRestauraveis=["perfis","familias","voluntarios","doadores","parceiros","visitas","areas_pastorais","campanhas_cestas","movimentacoes_cestas","distribuicoes_cestas","configuracoes","tesouraria_contas","tesouraria_categorias","tesouraria_movimentacoes","tesouraria_caixas","tesouraria_caixa_operacoes","secretaria_categorias_produtos","secretaria_produtos","secretaria_movimentacoes_estoque","secretaria_vendas","secretaria_servicos","secretaria_horarios_celebracoes","secretaria_eventos","secretaria_dizimistas","secretaria_dizimos_pagamentos","secretaria_registros_sacramentais","secretaria_registros_sacramentais_historico","secretaria_documentos_emitidos","secretaria_documentos_avulsos","secretaria_solicitacoes","secretaria_solicitacoes_historico","documentos","auditoria"] as const;

function erro(error:unknown){const mensagem=error instanceof Error?error.message:"Não foi possível processar a restauração.";return NextResponse.json({erro:mensagem},{status:mensagem==="UNAUTHENTICATED"?401:mensagem==="FORBIDDEN"?403:mensagem==="PARISH_REQUIRED"?409:400});}

export async function GET(request:NextRequest){try{const administrador=await exigirAdministrador(request);const{supabase,paroquiaId,paroquia}=await resolverParoquiaDaRequisicao(request,administrador);const contagens=await Promise.all(tabelasRestauraveis.map(async tabela=>{const{count,error}=await supabase.from(tabela).select("id",{count:"exact",head:true}).eq("paroquia_id",paroquiaId);if(error)throw error;return[tabela,count??0] as const;}));return NextResponse.json({paroquia:{id:paroquiaId,nome:paroquia.nome},contagens:Object.fromEntries(contagens),tabelas:tabelasRestauraveis});}catch(error){return erro(error);}}

export async function POST(request:NextRequest){try{const administrador=await exigirAdministrador(request);const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(request,administrador);const corpo=await request.json() as {paroquiaId?:string;tabela?:string;registros?:unknown[];confirmacao?:string};if(corpo.paroquiaId!==paroquiaId)throw new Error("O backup pertence a outra paróquia.");if(!tabelasRestauraveis.includes(corpo.tabela as typeof tabelasRestauraveis[number]))throw new Error("Tabela não autorizada para restauração.");const tabela=corpo.tabela as typeof tabelasRestauraveis[number];if(corpo.confirmacao!=="RESTAURAR_AUSENTES")throw new Error("Confirmação de restauração inválida.");if(!Array.isArray(corpo.registros)||corpo.registros.length>100)throw new Error("Lote inválido. Envie no máximo 100 registros.");const registros=corpo.registros.map(registro=>{if(!registro||typeof registro!=="object")throw new Error("Registro inválido no backup.");const item=registro as Record<string,unknown>;if(!item.id)throw new Error("Registro sem identificador.");if(item.paroquia_id!==paroquiaId)throw new Error("Registro pertence a outra paróquia.");return item;});if(!registros.length)return NextResponse.json({inseridos:0});const{data,error}=await supabase.from(tabela).upsert(registros,{onConflict:"id",ignoreDuplicates:true}).select("id");if(error)throw error;const inseridos=data?.length??0;if(inseridos){const auditoria={acao:"RESTAURAÇÃO",entidade:"BACKUP",entidadeId:paroquiaId,descricao:`Restauração segura: ${inseridos} registro(s) ausente(s) inserido(s) em ${tabela}.`,usuarioId:administrador.uid,usuarioNome:administrador.nome,usuarioEmail:administrador.email,paroquiaId,data:new Date().toISOString()};const registro=await supabase.from("auditoria").insert({id:randomUUID(),paroquia_id:paroquiaId,dados:auditoria});if(registro.error)throw registro.error;}return NextResponse.json({inseridos});}catch(error){return erro(error);}}
