import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
type Contexto={params:Promise<{id:string}>};const emitir=z.object({tipo:z.enum(["CERTIDAO","SEGUNDA_VIA"]),motivo:z.string().trim().max(300)});const permitidos=["admin_plataforma","admin_paroquia","atendente_secretaria"];
function erro(e:unknown){const m=e instanceof Error?e.message:e&&typeof e==="object"&&"message" in e?String(e.message):"Erro interno.";return NextResponse.json({erro:m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:400});}
const map=(i:Record<string,unknown>)=>({id:i.id,sacramento:i.sacramento,pessoaNome:i.pessoa_nome,pessoaNascimento:i.pessoa_nascimento,pessoaNaturalidade:i.pessoa_naturalidade,paiNome:i.pai_nome,maeNome:i.mae_nome,padrinhos:i.padrinhos??[],dataSacramento:i.data_sacramento,celebrante:i.celebrante,localSacramento:i.local_sacramento,livro:i.livro,folha:i.folha,termo:i.termo,numeroRegistro:i.numero_registro,observacoes:i.observacoes});
export async function GET(req:NextRequest,ctx:Contexto){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const{supabase,paroquiaId,paroquia}=await resolverParoquiaDaRequisicao(req,u);const id=(await ctx.params).id;const[registro,emissoes]=await Promise.all([supabase.from("secretaria_registros_sacramentais").select("*").eq("id",id).eq("paroquia_id",paroquiaId).eq("ativo",true).single(),supabase.from("secretaria_documentos_emitidos").select("id,tipo,motivo,emitido_por_nome,created_at").eq("registro_id",id).eq("paroquia_id",paroquiaId).order("created_at",{ascending:false})]);if(registro.error)throw registro.error;if(emissoes.error)throw emissoes.error;let logoUrl:string|null=null;if(paroquia.logo_caminho){const a=await supabase.storage.from("agape-documentos").createSignedUrl(paroquia.logo_caminho,3600);if(!a.error)logoUrl=a.data.signedUrl;}return NextResponse.json({paroquia:{nome:paroquia.nome,endereco:paroquia.endereco,logoUrl},registro:map(registro.data),emissoes:(emissoes.data??[]).map(e=>({id:e.id,tipo:e.tipo,motivo:e.motivo,emitidoPorNome:e.emitido_por_nome,createdAt:e.created_at}))});}catch(e){return erro(e)}}
export async function POST(req:NextRequest,ctx:Contexto){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const d=emitir.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const id=(await ctx.params).id;const existe=await supabase.from("secretaria_registros_sacramentais").select("id").eq("id",id).eq("paroquia_id",paroquiaId).eq("ativo",true).single();if(existe.error)throw existe.error;const{data,error}=await supabase.from("secretaria_documentos_emitidos").insert({paroquia_id:paroquiaId,registro_id:id,tipo:d.tipo,motivo:d.motivo,emitido_por:u.uid,emitido_por_nome:u.nome}).select("id,created_at").single();if(error)throw error;await supabase.from("secretaria_registros_sacramentais_historico").insert({paroquia_id:paroquiaId,registro_id:id,acao:"EMISSAO_DOCUMENTO",descricao:d.tipo==="SEGUNDA_VIA"?"Segunda via da certidão emitida":"Certidão emitida",criado_por:u.uid,criado_por_nome:u.nome});return NextResponse.json({id:data.id,createdAt:data.created_at});}catch(e){return erro(e)}}
