import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
const schema = z.object({ itens: z.array(z.object({ produtoId: z.uuid(), quantidade: z.number().int().positive() })).min(1), formaPagamento: z.enum(["DINHEIRO", "PIX", "CARTAO", "CORTESIA"]), valorRecebido: z.number().min(0).nullable().optional() });
const permitidos = ["admin_plataforma", "admin_paroquia", "atendente_secretaria"];
function erro(error: unknown) { const mensagem = error instanceof Error ? error.message : "Erro interno."; return NextResponse.json({ erro: mensagem }, { status: mensagem === "UNAUTHENTICATED" ? 401 : mensagem === "FORBIDDEN" ? 403 : 400 }); }
export async function GET(request: NextRequest) { try { const usuario = await exigirUsuarioAtivo(request); if (!permitidos.includes(usuario.role)) throw new Error("FORBIDDEN"); const { supabase, paroquiaId } = await resolverParoquiaDaRequisicao(request, usuario); const inicio = new Date(); inicio.setHours(0,0,0,0); const { data, error } = await supabase.from("secretaria_vendas").select("id,total,forma_pagamento,valor_recebido,troco,itens,status,created_at").eq("paroquia_id", paroquiaId).gte("created_at", inicio.toISOString()).order("created_at", { ascending: false }); if (error) throw error; return NextResponse.json((data ?? []).map((item) => ({ id: item.id, total: Number(item.total), formaPagamento: item.forma_pagamento, valorRecebido: item.valor_recebido === null ? null : Number(item.valor_recebido), troco: Number(item.troco), itens: item.itens, status: item.status, createdAt: item.created_at }))); } catch (error) { return erro(error); } }
export async function POST(request: NextRequest) { try { const usuario = await exigirUsuarioAtivo(request); if (!permitidos.includes(usuario.role)) throw new Error("FORBIDDEN"); const dados = schema.parse(await request.json()); const { supabase, paroquiaId } = await resolverParoquiaDaRequisicao(request, usuario); const caixa=await supabase.from("tesouraria_caixas").select("id").eq("paroquia_id",paroquiaId).eq("atendente_id",usuario.uid).eq("status","ABERTO").single();if(caixa.error)throw new Error("Abra o caixa antes de registrar vendas."); const { data, error } = await supabase.rpc("registrar_venda_secretaria", { p_paroquia_id: paroquiaId, p_itens: dados.itens, p_forma_pagamento: dados.formaPagamento, p_valor_recebido: dados.valorRecebido ?? null, p_criado_por: usuario.uid,p_caixa_id:caixa.data.id }); if (error) throw error; return NextResponse.json({ id: data }, { status: 201 }); } catch (error) { return erro(error); } }
