"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { Building2, CalendarClock, CalendarDays, CalendarRange, ClipboardList, LayoutDashboard, ListTree, LogOut, Menu, Settings, ShieldCheck, ShoppingCart, Landmark, X } from "lucide-react";
import { sair } from "@/lib/auth/client-session";
import { useAuth } from "@/modules/auth/hooks/useAuth";

export function ModuleHeader({ titulo, cor = "blue" }: { titulo: string; cor?: "blue"|"emerald" }) {
  const { usuario } = useAuth(); const [aberto,setAberto]=useState(false); const pathname=usePathname(); const router=useRouter(); const admin=usuario?.role === "admin_plataforma" || usuario?.role === "admin_paroquia";
  const itens = admin ? [{nome:"Painel Pastoral",href:"/dashboard",icone:LayoutDashboard},{nome:"Balcão da Secretaria",href:"/secretaria",icone:ShoppingCart},{nome:"Agenda paroquial",href:"/secretaria/agenda",icone:CalendarRange},{nome:"Solicitações",href:"/secretaria/solicitacoes",icone:ClipboardList},{nome:"Pauta de intenções",href:"/secretaria/intencoes",icone:CalendarDays},{nome:"Agenda de celebrações",href:"/secretaria/celebracoes",icone:CalendarClock},{nome:"Serviços da Secretaria",href:"/secretaria/servicos",icone:ListTree},{nome:"Tesouraria",href:"/tesouraria",icone:Landmark},{nome:"Administração",href:"/administracao",icone:Settings},{nome:"Usuários",href:"/usuarios",icone:ShieldCheck}] : usuario?.role === "atendente_secretaria" ? [{nome:"Balcão da Secretaria",href:"/secretaria",icone:ShoppingCart},{nome:"Agenda paroquial",href:"/secretaria/agenda",icone:CalendarRange},{nome:"Solicitações",href:"/secretaria/solicitacoes",icone:ClipboardList},{nome:"Pauta de intenções",href:"/secretaria/intencoes",icone:CalendarDays}] : [{nome:"Tesouraria",href:"/tesouraria",icone:Landmark}];
  async function encerrar(){await sair();router.replace("/login");}
  return <><header className="sticky top-0 z-40 border-b bg-white px-4 py-3 shadow-sm"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><button onClick={()=>setAberto(true)} aria-label="Abrir menu" className="rounded-xl border p-3 text-slate-700"><Menu size={22}/></button><div><p className={`text-xs font-bold uppercase tracking-wide ${cor === "emerald" ? "text-emerald-600" : "text-blue-600"}`}>Ágape</p><h1 className="text-lg font-black text-slate-900">{titulo}</h1></div></div>{admin&&<Link href="/dashboard" className="hidden items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold text-slate-700 sm:flex"><Building2 size={18}/>Painel</Link>}</div></header>{aberto&&<div className="fixed inset-0 z-50"><button aria-label="Fechar menu" onClick={()=>setAberto(false)} className="absolute inset-0 bg-slate-950/45"/><aside className="relative flex h-full w-[85%] max-w-xs flex-col bg-white p-4 shadow-2xl"><div className="flex items-center justify-between border-b pb-4"><div><p className="font-black text-blue-700">Ágape</p><p className="text-xs text-slate-500">{usuario?.nome}</p></div><button onClick={()=>setAberto(false)} className="rounded-xl p-3" aria-label="Fechar"><X/></button></div><nav className="mt-4 flex-1 space-y-2">{itens.map(item=>{const Icon=item.icone;const ativo=pathname===item.href||(item.href!=="/secretaria"&&pathname.startsWith(`${item.href}/`));return <Link key={item.href} href={item.href} onClick={()=>setAberto(false)} className={`flex min-h-13 items-center gap-3 rounded-xl px-4 py-3 font-semibold ${ativo?"bg-blue-600 text-white":"text-slate-700 hover:bg-slate-100"}`}><Icon size={20}/>{item.nome}</Link>})}</nav><button onClick={()=>void encerrar()} className="flex min-h-13 items-center gap-3 rounded-xl border border-red-200 px-4 py-3 font-semibold text-red-700"><LogOut size={20}/>Sair</button></aside></div>}</>;
}
