import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
const base=z.object({nome:z.string().trim().min(3).max(100),valor:z.number().min(0),prazoDias:z.number().int().min(0).max(365),documentos:z.array(z.string().trim().min(2).max(120)).max(30)});const editar=base.extend({id:z.uuid(),ativo:z.boolean()});
const permitidos=["admin_plataforma","admin_paroquia","atendente_secretaria"];
function erro(e:unknown){const m=e instanceof Error?e.message:e&&typeof e==="object"&&"message" in e?String(e.message):"Erro interno.";return NextResponse.json({erro:/duplicate|unique/i.test(m)?"Já existe um serviço com esse nome.":m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:400});}
const map=(i:Record<string,unknown>)=>({id:i.id,codigo:i.codigo,nome:i.nome,valor:Number(i.valor),prazoDias:Number(i.prazo_dias),documentos:i.documentos??[],ativo:i.ativo});
export async function GET(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_servicos").select("id,nome,valor,prazo_dias,documentos,ativo").eq("paroquia_id",paroquiaId).order("nome");if(error)throw error;return NextResponse.json((data??[]).map(i=>map(i)));}catch(e){return erro(e)}}
export async function POST(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!["admin_plataforma","admin_paroquia"].includes(u.role))throw new Error("FORBIDDEN");const d=base.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const codigo=`PERSONALIZADO_${crypto.randomUUID().slice(0,8).toUpperCase()}`;const{data,error}=await supabase.from("secretaria_servicos").insert({paroquia_id:paroquiaId,codigo,nome:d.nome,valor:d.valor,prazo_dias:d.prazoDias,documentos:d.documentos}).select("*").single();if(error)throw error;return NextResponse.json(map(data),{status:201});}catch(e){return erro(e)}}
export async function PATCH(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!["admin_plataforma","admin_paroquia"].includes(u.role))throw new Error("FORBIDDEN");const d=editar.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_servicos").update({nome:d.nome,valor:d.valor,prazo_dias:d.prazoDias,documentos:d.documentos,ativo:d.ativo,updated_at:new Date().toISOString()}).eq("id",d.id).eq("paroquia_id",paroquiaId).select("*").single();if(error)throw error;return NextResponse.json(map(data));}catch(e){return erro(e)}}
