"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { enviarRecuperacaoSenha, obterTokenAcesso } from "@/lib/auth/client-session";
import { maskTelefone } from "@/lib/formatters/masks";
import { useAuth } from "@/modules/auth/hooks/useAuth";

type Administrador = { id: string; nome: string; email: string; telefone?: string; status: "ATIVO" | "INATIVO" };
async function requisicao<T>(url: string, init?: RequestInit): Promise<T> { const token = await obterTokenAcesso(); const resposta = await fetch(url, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` } }); const dados = await resposta.json(); if (!resposta.ok) throw new Error(dados.erro || "Não foi possível concluir a operação."); return dados as T; }

export default function AdministradoresPlataformaPage() {
  const router = useRouter(); const { usuario, carregando } = useAuth(); const [administradores, setAdministradores] = useState<Administrador[]>([]); const [form, setForm] = useState({ nome: "", email: "", telefone: "" }); const [salvando, setSalvando] = useState(false);
  const carregar = useCallback(async () => { try { setAdministradores(await requisicao<Administrador[]>("/api/administradores-plataforma")); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível carregar os administradores."); } }, []);
  useEffect(() => { if (!carregando && !usuario) router.replace("/login"); else if (!carregando && usuario?.role !== "admin_plataforma") router.replace("/dashboard"); }, [carregando, router, usuario]);
  useEffect(() => { if (usuario?.role === "admin_plataforma") void carregar(); }, [carregar, usuario]);
  async function cadastrar(event: FormEvent) { event.preventDefault(); setSalvando(true); try { await requisicao("/api/administradores-plataforma", { method: "POST", body: JSON.stringify(form) }); await enviarRecuperacaoSenha(form.email); toast.success("Administrador criado. Enviamos o e-mail para definição de senha."); setForm({ nome: "", email: "", telefone: "" }); await carregar(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível cadastrar."); } finally { setSalvando(false); } }
  async function alternar(item: Administrador) { const status = item.status === "ATIVO" ? "INATIVO" : "ATIVO"; try { await requisicao(`/api/administradores-plataforma/${item.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); toast.success(status === "ATIVO" ? "Administrador ativado." : "Administrador inativado."); await carregar(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível alterar o acesso."); } }
  if (carregando || usuario?.role !== "admin_plataforma") return <div className="flex min-h-screen items-center justify-center bg-slate-100 text-slate-500">Verificando acesso...</div>;
  return <main className="min-h-screen bg-slate-100"><header className="border-b bg-white px-8 py-5"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><h1 className="text-2xl font-bold text-blue-700">Administrar logins</h1><p className="text-sm text-slate-500">Administradores com acesso geral à plataforma e a todas as paróquias.</p></div><Link href="/central" className="rounded-lg border px-4 py-2 font-medium text-slate-700">Voltar à Central</Link></div></header><div className="mx-auto grid max-w-6xl gap-6 p-8 lg:grid-cols-[380px_1fr]"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Novo administrador</h2><form onSubmit={cadastrar} className="mt-5 space-y-4"><label className="block text-sm font-medium">Nome completo<input value={form.nome} onChange={(e) => setForm({ ...form, nome: e.target.value })} className="mt-2 w-full rounded-lg border px-4 py-3 font-normal" required /></label><label className="block text-sm font-medium">E-mail<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-2 w-full rounded-lg border px-4 py-3 font-normal" required /></label><label className="block text-sm font-medium">Telefone<input value={form.telefone} onChange={(e) => setForm({ ...form, telefone: maskTelefone(e.target.value) })} maxLength={15} className="mt-2 w-full rounded-lg border px-4 py-3 font-normal" placeholder="(11) 99999-9999" /></label><button disabled={salvando} className="w-full rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{salvando ? "Criando..." : "Criar administrador"}</button></form></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Administradores gerais</h2><div className="mt-5 space-y-3">{administradores.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><p className="font-semibold">{item.nome}</p><p className="text-sm text-slate-500">{item.email}</p><span className={`mt-2 inline-block rounded-full px-2.5 py-1 text-xs font-semibold ${item.status === "ATIVO" ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700"}`}>{item.status === "ATIVO" ? "Ativo" : "Inativo"}</span></div><button type="button" disabled={item.id === usuario.uid} onClick={() => void alternar(item)} className="rounded-lg border px-3 py-2 text-sm font-medium text-blue-700 disabled:cursor-not-allowed disabled:opacity-40">{item.id === usuario.uid ? "Conta atual" : item.status === "ATIVO" ? "Inativar" : "Ativar"}</button></article>)}</div></section></div></main>;
}
