"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Minus, Plus, Search, ShoppingBag, ShoppingCart, LogOut, PackagePlus, ReceiptText } from "lucide-react";
import toast from "react-hot-toast";
import { ProtectedArea } from "@/components/auth/ProtectedArea";
import { obterTokenAcesso, sair } from "@/lib/auth/client-session";
import { useAuth } from "@/modules/auth/hooks/useAuth";
import { FormaPagamento, ItemCarrinho, ProdutoSecretaria, VendaSecretaria } from "@/modules/secretaria/types";
async function api<T>(url: string, init?: RequestInit): Promise<T> { const token = await obterTokenAcesso(); const resposta = await fetch(url, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...init?.headers } }); const dados = await resposta.json(); if (!resposta.ok) throw new Error(dados.erro || "Não foi possível concluir a operação."); return dados as T; }
const moeda = (valor: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(valor);
function SecretariaConteudo() {
  const { usuario } = useAuth(); const administrador = usuario?.role === "admin_plataforma" || usuario?.role === "admin_paroquia";
  const [produtos, setProdutos] = useState<ProdutoSecretaria[]>([]); const [vendas, setVendas] = useState<VendaSecretaria[]>([]); const [carrinho, setCarrinho] = useState<ItemCarrinho[]>([]); const [busca, setBusca] = useState(""); const [aba, setAba] = useState<"BALCAO"|"PRODUTOS"|"HISTORICO">("BALCAO"); const [pagamento, setPagamento] = useState<FormaPagamento>("PIX"); const [recebido, setRecebido] = useState(""); const [finalizando, setFinalizando] = useState(false); const [novo, setNovo] = useState({ nome: "", categoria: "Outros", preco: "", estoque: "" });
  const carregar = useCallback(async () => { try { const [catalogo, historico] = await Promise.all([api<ProdutoSecretaria[]>("/api/secretaria/produtos"), api<VendaSecretaria[]>("/api/secretaria/vendas")]); setProdutos(catalogo); setVendas(historico); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível carregar o balcão."); } }, []);
  useEffect(() => { void carregar(); }, [carregar]);
  const total = carrinho.reduce((soma, item) => soma + item.produto.preco * item.quantidade, 0); const valorRecebido = Number(recebido.replace(",", ".")) || 0; const troco = pagamento === "DINHEIRO" ? Math.max(0, valorRecebido - total) : 0;
  const filtrados = useMemo(() => { const termo = busca.trim().toLowerCase(); return produtos.filter((item) => item.ativo && item.estoque > 0 && (!termo || `${item.nome} ${item.categoria}`.toLowerCase().includes(termo))); }, [busca, produtos]);
  function alterar(produto: ProdutoSecretaria, delta: number) { setCarrinho((atual) => { const existente = atual.find((item) => item.produto.id === produto.id); const quantidade = Math.min(produto.estoque, Math.max(0, (existente?.quantidade || 0) + delta)); if (!quantidade) return atual.filter((item) => item.produto.id !== produto.id); return existente ? atual.map((item) => item.produto.id === produto.id ? { ...item, quantidade } : item) : [...atual, { produto, quantidade }]; }); }
  async function finalizar() { if (!carrinho.length) return toast.error("Adicione ao menos um produto."); if (pagamento === "DINHEIRO" && valorRecebido < total) return toast.error("O valor recebido é menor que o total."); setFinalizando(true); try { await api("/api/secretaria/vendas", { method: "POST", body: JSON.stringify({ itens: carrinho.map((item) => ({ produtoId: item.produto.id, quantidade: item.quantidade })), formaPagamento: pagamento, valorRecebido: pagamento === "DINHEIRO" ? valorRecebido : null }) }); toast.success("Venda concluída e estoque atualizado."); setCarrinho([]); setRecebido(""); await carregar(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível finalizar a venda."); } finally { setFinalizando(false); } }
  async function cadastrarProduto(event: FormEvent) { event.preventDefault(); try { await api("/api/secretaria/produtos", { method: "POST", body: JSON.stringify({ ...novo, preco: Number(novo.preco.replace(",", ".")), estoque: Number(novo.estoque) }) }); toast.success("Produto cadastrado."); setNovo({ nome: "", categoria: "Outros", preco: "", estoque: "" }); await carregar(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível cadastrar."); } }
  return <main className="min-h-screen bg-slate-100 pb-40"><header className="sticky top-0 z-20 border-b bg-white px-4 py-3 shadow-sm"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">Ágape</p><h1 className="text-lg font-bold text-slate-900">Secretaria Paroquial</h1></div><button onClick={() => void sair().then(() => location.assign("/login"))} aria-label="Sair" className="rounded-xl border p-3 text-slate-600"><LogOut size={21}/></button></div></header>
  <div className="mx-auto max-w-6xl p-4"><nav className="mb-5 grid grid-cols-3 gap-2 rounded-2xl bg-white p-2 shadow-sm">{([["BALCAO","Balcão",ShoppingCart],["HISTORICO","Hoje",ReceiptText],...(administrador ? [["PRODUTOS","Produtos",PackagePlus]] : [])] as Array<[typeof aba,string,typeof ShoppingCart]>).map(([id,label,Icon]) => <button key={id} onClick={() => setAba(id)} className={`flex min-h-14 items-center justify-center gap-2 rounded-xl text-sm font-semibold ${aba === id ? "bg-blue-600 text-white" : "text-slate-600"}`}><Icon size={19}/>{label}</button>)}</nav>
  {aba === "BALCAO" && <div className="space-y-4"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={21}/><input type="search" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar produto..." className="min-h-14 w-full rounded-2xl border bg-white pl-12 pr-4 text-base shadow-sm"/></div><section className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{filtrados.map((produto) => { const quantidade = carrinho.find((item) => item.produto.id === produto.id)?.quantidade || 0; return <article key={produto.id} className="flex min-h-44 flex-col justify-between rounded-2xl border bg-white p-4 shadow-sm"><div><span className="text-xs font-medium text-blue-600">{produto.categoria}</span><h2 className="mt-1 font-bold text-slate-900">{produto.nome}</h2><p className="mt-2 text-xl font-black text-slate-900">{moeda(produto.preco)}</p><p className="text-xs text-slate-500">Estoque: {produto.estoque}</p></div><div className="mt-3 flex items-center justify-between"><button onClick={() => alterar(produto,-1)} className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100" aria-label="Remover"><Minus/></button><strong className="text-lg">{quantidade}</strong><button onClick={() => alterar(produto,1)} className="grid h-11 w-11 place-items-center rounded-xl bg-blue-600 text-white" aria-label="Adicionar"><Plus/></button></div></article>; })}</section>{!filtrados.length && <div className="rounded-2xl bg-white p-8 text-center text-slate-500"><ShoppingBag className="mx-auto mb-2"/>Nenhum produto disponível.</div>}</div>}
  {aba === "HISTORICO" && <section className="space-y-3"><div className="rounded-2xl bg-blue-700 p-5 text-white"><p className="text-sm text-blue-100">Total vendido hoje</p><p className="mt-1 text-3xl font-black">{moeda(vendas.filter((v) => v.status === "CONCLUIDA").reduce((s,v) => s + v.total,0))}</p><p className="text-sm text-blue-100">{vendas.length} venda(s)</p></div>{vendas.map((venda) => <article key={venda.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><p className="font-bold">{venda.itens.map((i) => `${i.quantidade}x ${i.nome}`).join(", ")}</p><p className="mt-1 text-xs text-slate-500">{new Date(venda.createdAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })} • {venda.formaPagamento}</p></div><strong>{moeda(venda.total)}</strong></div></article>)}</section>}
  {aba === "PRODUTOS" && administrador && <section className="space-y-4"><form onSubmit={cadastrarProduto} className="space-y-3 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Novo produto</h2><input value={novo.nome} onChange={(e) => setNovo({...novo,nome:e.target.value})} placeholder="Nome do produto" className="min-h-12 w-full rounded-xl border px-4" required/><input value={novo.categoria} onChange={(e) => setNovo({...novo,categoria:e.target.value})} placeholder="Categoria" className="min-h-12 w-full rounded-xl border px-4" required/><div className="grid grid-cols-2 gap-3"><input inputMode="decimal" value={novo.preco} onChange={(e) => setNovo({...novo,preco:e.target.value})} placeholder="Preço" className="min-h-12 w-full rounded-xl border px-4" required/><input inputMode="numeric" value={novo.estoque} onChange={(e) => setNovo({...novo,estoque:e.target.value})} placeholder="Estoque" className="min-h-12 w-full rounded-xl border px-4" required/></div><button className="min-h-12 w-full rounded-xl bg-blue-600 font-bold text-white">Cadastrar produto</button></form><div className="space-y-2">{produtos.map((produto) => <div key={produto.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><strong>{produto.nome}</strong><p className="text-sm text-slate-500">{moeda(produto.preco)} • estoque {produto.estoque}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${produto.ativo ? "bg-emerald-100 text-emerald-700" : "bg-slate-200"}`}>{produto.ativo ? "Ativo" : "Inativo"}</span></div>)}</div></section>}</div>
  {aba === "BALCAO" && carrinho.length > 0 && <aside className="fixed inset-x-0 bottom-0 z-30 border-t bg-white p-3 shadow-2xl"><div className="mx-auto max-w-6xl"><div className="mb-2 flex items-center justify-between"><span className="text-sm text-slate-500">{carrinho.reduce((s,i) => s+i.quantidade,0)} item(ns)</span><strong className="text-2xl">{moeda(total)}</strong></div><div className="grid grid-cols-4 gap-2">{(["DINHEIRO","PIX","CARTAO","CORTESIA"] as FormaPagamento[]).map((forma) => <button key={forma} onClick={() => setPagamento(forma)} className={`min-h-10 rounded-lg text-xs font-bold ${pagamento === forma ? "bg-blue-100 text-blue-700 ring-2 ring-blue-600" : "bg-slate-100 text-slate-600"}`}>{forma === "CARTAO" ? "CARTÃO" : forma}</button>)}</div>{pagamento === "DINHEIRO" && <div className="mt-2 flex items-center gap-2"><input inputMode="decimal" value={recebido} onChange={(e) => setRecebido(e.target.value)} placeholder="Valor recebido" className="min-h-12 flex-1 rounded-xl border px-4"/><span className="text-sm font-semibold">Troco: {moeda(troco)}</span></div>}<button onClick={() => void finalizar()} disabled={finalizando} className="mt-3 min-h-14 w-full rounded-xl bg-emerald-600 text-lg font-black text-white disabled:opacity-60">{finalizando ? "Finalizando..." : "Finalizar venda"}</button></div></aside>}
  </main>;
}
export default function SecretariaPage() { return <ProtectedArea><SecretariaConteudo/></ProtectedArea>; }
