"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback,useEffect,useState } from "react";
import { ArrowLeft,CheckCircle2,Circle,Mail,Printer } from "lucide-react";
import toast from "react-hot-toast";
import { ProtectedArea } from "@/components/auth/ProtectedArea";
import { ModuleHeader } from "@/components/layout/ModuleHeader";
import { obterTokenAcesso } from "@/lib/auth/client-session";
import { DocumentoChecklist,HistoricoSolicitacao,SolicitacaoSecretaria,StatusSolicitacao } from "@/modules/secretaria/solicitacoes-types";

const statuses:Record<StatusSolicitacao,string>={RECEBIDA:"Recebida",EM_ANDAMENTO:"Em andamento",AGUARDANDO_DOCUMENTOS:"Aguardando documentos",PRONTA:"Pronta",CONCLUIDA:"Concluída",CANCELADA:"Cancelada"};
const moeda=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
const data=(v?:string|null)=>v?new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString("pt-BR"):"Não informada";

function Conteudo(){
  const params=useParams<{id:string}>();
  const[dados,setDados]=useState<{paroquia:{nome:string};solicitacao:SolicitacaoSecretaria;historico:HistoricoSolicitacao[]}|null>(null);const[salvando,setSalvando]=useState(false);
  const carregar=useCallback(async()=>{try{const token=await obterTokenAcesso();const resposta=await fetch(`/api/secretaria/solicitacoes/${params.id}`,{headers:{Authorization:`Bearer ${token}`}});const json=await resposta.json();if(!resposta.ok)throw new Error(json.erro);setDados(json);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível carregar o protocolo.");}},[params.id]);
  useEffect(()=>{void carregar();},[carregar]);
  async function patch(body:unknown){const token=await obterTokenAcesso();const resposta=await fetch(`/api/secretaria/solicitacoes/${params.id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const json=await resposta.json();if(!resposta.ok)throw new Error(json.erro);return json;}
  async function salvarDocumentos(documentos:DocumentoChecklist[]){if(!dados)return;setDados({...dados,solicitacao:{...dados.solicitacao,documentosChecklist:documentos}});setSalvando(true);try{await patch({acao:"DOCUMENTOS",documentos});toast.success("Checklist atualizado.");}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível atualizar.");await carregar();}finally{setSalvando(false);}}
  async function imprimir(){try{const registro=await patch({acao:"IMPRIMIR"});if(dados)setDados({...dados,solicitacao:{...dados.solicitacao,impressoEm:registro.impressoEm,impressoPorNome:registro.impressoPorNome}});setTimeout(()=>window.print(),100);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível registrar a impressão.");}}
  if(!dados)return <div className="grid min-h-screen place-items-center bg-slate-100">Carregando protocolo...</div>;
  const s=dados.solicitacao;const documentos=s.documentosChecklist??[];const entregues=documentos.filter(d=>d.entregue).length;const intencao=s.tipo==="INTENCAO_MISSA";const assunto=encodeURIComponent(`${dados.paroquia.nome} — Protocolo ${s.protocolo}`);const corpo=encodeURIComponent(`Olá, ${s.solicitanteNome}.\n\nSegue o resumo da sua solicitação:\nProtocolo: ${s.protocolo}\nServiço: ${s.servicoNome||s.tipo}\nInteressado: ${s.interessadoNome||"Não informado"}\nPrazo: ${data(s.prazo)}\nStatus: ${statuses[s.status]}\n\n${dados.paroquia.nome}`);const email=`mailto:${s.solicitanteEmail||""}?subject=${assunto}&body=${corpo}`;
  return <main className="min-h-screen bg-slate-100 print:bg-white"><div className="print:hidden"><ModuleHeader titulo={`Protocolo ${s.protocolo}`}/></div><div className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6 print:max-w-none print:p-0"><div className="flex flex-wrap items-center justify-between gap-2 print:hidden"><Link href="/secretaria/solicitacoes" className="inline-flex min-h-11 items-center gap-2 rounded-lg border bg-white px-4 font-semibold"><ArrowLeft size={18}/>Voltar</Link><div className="flex flex-wrap gap-2"><a href={email} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-blue-600 px-4 font-semibold text-white"><Mail size={18}/>Enviar por e-mail</a><button onClick={()=>void imprimir()} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-slate-900 px-4 font-semibold text-white"><Printer size={18}/>{intencao?"Imprimir intenção":"Imprimir protocolo"}</button></div></div>
    <header className="rounded-2xl border bg-white p-6 print:border-0 print:p-0"><p className="text-sm font-bold uppercase text-blue-600">{dados.paroquia.nome}</p><h1 className="mt-1 text-2xl font-black">{intencao?"Intenção de missa":`Protocolo ${s.protocolo}`}</h1><p className="text-slate-500">{s.servicoNome||s.tipo} • {statuses[s.status]}</p>{intencao&&<section className="my-6 rounded-2xl border-2 border-violet-200 bg-violet-50 p-5 print:border-slate-800 print:bg-white"><p className="text-xs font-bold uppercase text-violet-700 print:text-black">Intenção</p><p className="mt-2 text-2xl font-black">{s.detalhes?.nomeIntencao}</p><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3"><p><span className="block text-xs font-bold uppercase text-slate-500">Tipo</span>{s.detalhes?.tipo}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Celebração</span>{data(s.detalhes?.dataCelebracao)}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Horário</span>{s.detalhes?.horario||"A definir"}</p></div></section>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><p><span className="block text-xs font-bold uppercase text-slate-500">Protocolo</span>{s.protocolo}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Solicitante</span>{s.solicitanteNome}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Interessado</span>{s.interessadoNome||"Não informado"}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Contato</span>{s.telefone||"Não informado"}{s.solicitanteEmail&&` • ${s.solicitanteEmail}`}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Prazo</span>{data(s.prazo)}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Taxa</span>{moeda(s.valor)} • {s.valor===0?"Sem cobrança":s.pago?"Pago":"Pendente"}</p><p><span className="block text-xs font-bold uppercase text-slate-500">Recebido em</span>{new Date(s.createdAt).toLocaleString("pt-BR")}</p>{s.impressoEm&&<p><span className="block text-xs font-bold uppercase text-slate-500">Última impressão</span>{new Date(s.impressoEm).toLocaleString("pt-BR")} por {s.impressoPorNome}</p>}</div>{s.observacoes&&<div className="mt-4 rounded-xl bg-slate-50 p-4"><span className="text-xs font-bold uppercase text-slate-500">Observações</span><p>{s.observacoes}</p></div>}</header>
    {!intencao&&<section className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Documentos necessários</h2><p className="text-sm text-slate-500">{entregues} de {documentos.length} entregues</p></div>{salvando&&<span className="text-sm text-blue-600">Salvando...</span>}</div><div className="mt-4 space-y-2">{documentos.map(doc=><button type="button" key={doc.id} disabled={salvando} onClick={()=>void salvarDocumentos(documentos.map(item=>item.id===doc.id?{...item,entregue:!item.entregue}:item))} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left print:border-0 print:p-1 ${doc.entregue?"bg-emerald-50 text-emerald-800":"bg-white"}`}>{doc.entregue?<CheckCircle2 className="shrink-0"/>:<Circle className="shrink-0 text-slate-300"/>}<span className={doc.entregue?"line-through":""}>{doc.nome}</span></button>)}{!documentos.length&&<p className="text-sm text-slate-500">Este serviço não possui documentos obrigatórios cadastrados.</p>}</div></section>}
    <section className="rounded-2xl border bg-white p-6 print:hidden"><h2 className="text-xl font-black">Histórico do atendimento</h2><div className="mt-4 space-y-4 border-l-2 border-slate-200 pl-4">{dados.historico.map(h=><div key={h.id}><p className="font-bold">{statuses[h.status as StatusSolicitacao]||h.status}</p><p className="text-sm text-slate-600">{h.observacao}</p><p className="text-xs text-slate-400">{h.criadoPorNome} • {new Date(h.createdAt).toLocaleString("pt-BR")}</p></div>)}</div></section><footer className="hidden border-t pt-8 text-sm print:block"><p>Impresso em {new Date().toLocaleString("pt-BR")} • Responsável: {s.impressoPorNome||s.criadoPorNome}</p><div className="mt-16 grid grid-cols-2 gap-16 text-center"><p className="border-t pt-2">Secretaria paroquial</p><p className="border-t pt-2">Solicitante</p></div></footer></div></main>;
}

export default function ProtocoloPage(){return <ProtectedArea><Conteudo/></ProtectedArea>}
