import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
const schema=z.discriminatedUnion("acao",[z.object({acao:z.literal("ABRIR"),contaId:z.uuid(),fundoAbertura:z.number().min(0)}),z.object({acao:z.literal("OPERACAO"),tipo:z.enum(["REFORCO","SANGRIA"]),valor:z.number().positive(),descricao:z.string().trim().min(3)}),z.object({acao:z.literal("FECHAR"),valorContado:z.number().min(0),observacao:z.string().trim()}),z.object({acao:z.literal("CONFERIR"),caixaId:z.uuid(),observacao:z.string().trim()})]);
const perfis=["admin_plataforma","admin_paroquia","tesoureiro","atendente_secretaria"];
async function contexto(req:NextRequest){const usuario=await exigirUsuarioAtivo(req);if(!perfis.includes(usuario.role))throw new Error("FORBIDDEN");return{usuario,...await resolverParoquiaDaRequisicao(req,usuario)}}
function erro(e:unknown){const m=e instanceof Error?e.message:"Erro interno.";return NextResponse.json({erro:m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:400})}
async function totais(supabase:ReturnType<(typeof import("@/lib/supabase/admin"))["supabaseAdmin"]>,caixaId:string,fundo:number){const[vendas,operacoes]=await Promise.all([supabase.from("secretaria_vendas").select("total").eq("caixa_id",caixaId).eq("status","CONCLUIDA").eq("forma_pagamento","DINHEIRO"),supabase.from("tesouraria_caixa_operacoes").select("tipo,valor").eq("caixa_id",caixaId)]);if(vendas.error)throw vendas.error;if(operacoes.error)throw operacoes.error;const vendasDinheiro=(vendas.data??[]).reduce((s,i)=>s+Number(i.total),0);const reforcos=(operacoes.data??[]).filter(i=>i.tipo==="REFORCO").reduce((s,i)=>s+Number(i.valor),0);const sangrias=(operacoes.data??[]).filter(i=>i.tipo==="SANGRIA").reduce((s,i)=>s+Number(i.valor),0);return{vendasDinheiro,reforcos,sangrias,valorEsperado:fundo+vendasDinheiro+reforcos-sangrias,operacoes:operacoes.data??[]}}
export async function GET(req:NextRequest){try{const{usuario,supabase,paroquiaId}=await contexto(req);const historico=new URL(req.url).searchParams.get("historico")==="1";const contas=await supabase.from("tesouraria_contas").select("id,nome").eq("paroquia_id",paroquiaId).eq("tipo","CAIXA").eq("ativa",true).order("nome");if(contas.error)throw contas.error;if(historico&&["admin_plataforma","admin_paroquia","tesoureiro"].includes(usuario.role)){const lista=await supabase.from("tesouraria_caixas").select("*,tesouraria_contas(nome)").eq("paroquia_id",paroquiaId).neq("status","ABERTO").order("aberto_em",{ascending:false}).limit(100);if(lista.error)throw lista.error;return NextResponse.json({contas:contas.data??[],historico:lista.data??[]});}const caixa=await supabase.from("tesouraria_caixas").select("*,tesouraria_contas(nome)").eq("paroquia_id",paroquiaId).eq("atendente_id",usuario.uid).eq("status","ABERTO").maybeSingle();if(caixa.error)throw caixa.error;if(!caixa.data)return NextResponse.json({contas:contas.data??[],caixa:null});return NextResponse.json({contas:contas.data??[],caixa:{...caixa.data,...await totais(supabase,caixa.data.id,Number(caixa.data.fundo_abertura))}});}catch(e){return erro(e)}}
export async function POST(req:NextRequest){try{const{usuario,supabase,paroquiaId}=await contexto(req);const d=schema.parse(await req.json());if(d.acao==="ABRIR"){const conta=await supabase.from("tesouraria_contas").select("id").eq("id",d.contaId).eq("paroquia_id",paroquiaId).eq("tipo","CAIXA").eq("ativa",true).single();if(conta.error)throw new Error("Selecione uma conta Caixa ativa.");const criado=await supabase.from("tesouraria_caixas").insert({paroquia_id:paroquiaId,conta_id:d.contaId,atendente_id:usuario.uid,atendente_nome:usuario.nome,fundo_abertura:d.fundoAbertura}).select("id").single();if(criado.error)throw criado.error;return NextResponse.json({id:criado.data.id},{status:201});}if(d.acao==="CONFERIR"){if(!["admin_plataforma","admin_paroquia","tesoureiro"].includes(usuario.role))throw new Error("FORBIDDEN");const atualizado=await supabase.from("tesouraria_caixas").update({status:"CONFERIDO",conferido_por:usuario.uid,conferido_em:new Date().toISOString(),observacao_conferencia:d.observacao,updated_at:new Date().toISOString()}).eq("id",d.caixaId).eq("paroquia_id",paroquiaId).eq("status","FECHADO");if(atualizado.error)throw atualizado.error;return NextResponse.json({id:d.caixaId});}const caixa=await supabase.from("tesouraria_caixas").select("id,fundo_abertura").eq("paroquia_id",paroquiaId).eq("atendente_id",usuario.uid).eq("status","ABERTO").single();if(caixa.error)throw new Error("Não há caixa aberto para este usuário.");if(d.acao==="OPERACAO"){const op=await supabase.from("tesouraria_caixa_operacoes").insert({paroquia_id:paroquiaId,caixa_id:caixa.data.id,tipo:d.tipo,valor:d.valor,descricao:d.descricao,criado_por:usuario.uid}).select("id").single();if(op.error)throw op.error;return NextResponse.json({id:op.data.id},{status:201});}const t=await totais(supabase,caixa.data.id,Number(caixa.data.fundo_abertura));const diferenca=d.valorContado-t.valorEsperado;if(Math.abs(diferenca)>=0.01&&!d.observacao)throw new Error("Informe uma justificativa para a diferença de caixa.");const fechado=await supabase.from("tesouraria_caixas").update({status:"FECHADO",fechado_em:new Date().toISOString(),valor_esperado:t.valorEsperado,valor_contado:d.valorContado,diferenca,observacao_fechamento:d.observacao,updated_at:new Date().toISOString()}).eq("id",caixa.data.id).eq("status","ABERTO");if(fechado.error)throw fechado.error;return NextResponse.json({id:caixa.data.id,valorEsperado:t.valorEsperado,diferenca});}catch(e){return erro(e)}}
