import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
const tipos=["BATISMO","CASAMENTO","CURSO","REUNIAO","CELEBRACAO","ATENDIMENTO","OUTRO"] as const;const statuses=["AGENDADO","CONFIRMADO","CONCLUIDO","CANCELADO"] as const;
const base=z.object({titulo:z.string().trim().min(3).max(120),tipo:z.enum(tipos),inicio:z.iso.datetime(),fim:z.iso.datetime(),local:z.string().trim().max(120),responsavel:z.string().trim().max(120),observacoes:z.string().trim().max(1000),ignorarConflito:z.boolean().optional()}).refine(d=>new Date(d.fim)>new Date(d.inicio),{message:"O término deve ser posterior ao início."});const editar=base.extend({id:z.uuid(),status:z.enum(statuses)});
const permitidos=["admin_plataforma","admin_paroquia","atendente_secretaria"];
const map=(i:Record<string,unknown>)=>({id:i.id,titulo:i.titulo,tipo:i.tipo,inicio:i.inicio,fim:i.fim,local:i.local||"",responsavel:i.responsavel||"",observacoes:i.observacoes||"",status:i.status,criadoPorNome:i.criado_por_nome});
function erro(e:unknown,status=400){const m=e instanceof Error?e.message:e&&typeof e==="object"&&"message" in e?String(e.message):"Erro interno.";return NextResponse.json({erro:m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:status});}
async function conflito(supabase:ReturnType<typeof import("@/lib/supabase/admin").supabaseAdmin>,paroquiaId:string,inicio:string,fim:string,id?:string){let q=supabase.from("secretaria_eventos").select("id,titulo,inicio,fim").eq("paroquia_id",paroquiaId).neq("status","CANCELADO").lt("inicio",fim).gt("fim",inicio);if(id)q=q.neq("id",id);return q.limit(5);}
export async function GET(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const inicio=req.nextUrl.searchParams.get("inicio"),fim=req.nextUrl.searchParams.get("fim");if(!inicio||!fim)throw new Error("Informe o período da agenda.");const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_eventos").select("*").eq("paroquia_id",paroquiaId).lt("inicio",fim).gt("fim",inicio).order("inicio");if(error)throw error;return NextResponse.json((data??[]).map(i=>map(i)));}catch(e){return erro(e)}}
export async function POST(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const d=base.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);if(!d.ignorarConflito){const c=await conflito(supabase,paroquiaId,d.inicio,d.fim);if(c.error)throw c.error;if(c.data?.length)return NextResponse.json({erro:"Já existe um compromisso nesse período.",conflitos:c.data},{status:409});}const{data,error}=await supabase.from("secretaria_eventos").insert({paroquia_id:paroquiaId,titulo:d.titulo,tipo:d.tipo,inicio:d.inicio,fim:d.fim,local:d.local,responsavel:d.responsavel,observacoes:d.observacoes,criado_por:u.uid,criado_por_nome:u.nome}).select("*").single();if(error)throw error;return NextResponse.json(map(data),{status:201});}catch(e){return erro(e)}}
export async function PATCH(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const d=editar.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);if(!d.ignorarConflito&&d.status!=="CANCELADO"){const c=await conflito(supabase,paroquiaId,d.inicio,d.fim,d.id);if(c.error)throw c.error;if(c.data?.length)return NextResponse.json({erro:"Já existe um compromisso nesse período.",conflitos:c.data},{status:409});}const{data,error}=await supabase.from("secretaria_eventos").update({titulo:d.titulo,tipo:d.tipo,inicio:d.inicio,fim:d.fim,local:d.local,responsavel:d.responsavel,observacoes:d.observacoes,status:d.status,updated_at:new Date().toISOString()}).eq("id",d.id).eq("paroquia_id",paroquiaId).select("*").single();if(error)throw error;return NextResponse.json(map(data));}catch(e){return erro(e)}}
