"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { BookOpen,FileText,History,Pencil,Plus,Search } from "lucide-react";
import toast from "react-hot-toast";
import { ProtectedArea } from "@/components/auth/ProtectedArea";
import { ModuleHeader } from "@/components/layout/ModuleHeader";
import { obterTokenAcesso } from "@/lib/auth/client-session";

type Registro={id:string;sacramento:string;pessoaNome:string;pessoaNascimento:string|null;pessoaNaturalidade:string;paiNome:string;maeNome:string;padrinhos:string[];dadosEspecificos:Record<string,string>;dataSacramento:string;celebrante:string;localSacramento:string;livro:string;folha:string;termo:string;numeroRegistro:string;observacoes:string;ativo:boolean;criadoPorNome:string;createdAt:string};type Historico={id:string;descricao:string;criadoPorNome:string;createdAt:string};
const nomes:Record<string,string>={BATISMO:"Batismo",PRIMEIRA_COMUNHAO:"Primeira Comunhão",CRISMA:"Crisma",MATRIMONIO:"Matrimônio"};
const vazio=()=>({id:"",sacramento:"BATISMO",pessoaNome:"",pessoaNascimento:"",pessoaNaturalidade:"",paiNome:"",maeNome:"",padrinho1:"",padrinho2:"",dataSacramento:"",celebrante:"",localSacramento:"",livro:"",folha:"",termo:"",numeroRegistro:"",observacoes:"",ativo:true,dadosEspecificos:{} as Record<string,string>});
async function api<T>(url="",init?:RequestInit){const token=await obterTokenAcesso();const r=await fetch(`/api/secretaria/sacramentos${url}`,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.erro||"Operação não concluída.");return d as T;}
function Campo({label,valor,onChange,type="text",required=false}:{label:string;valor:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="text-sm font-bold">{label}<input type={type} value={valor} onChange={e=>onChange(e.target.value)} className="mt-1 min-h-12 w-full rounded-xl border px-3 font-normal" required={required}/></label>}

function Conteudo(){
  const[registros,setRegistros]=useState<Registro[]>([]);const[busca,setBusca]=useState("");const[filtro,setFiltro]=useState("TODOS");const[form,setForm]=useState(vazio);const[aberto,setAberto]=useState(false);const[detalhe,setDetalhe]=useState<{registro:Registro;historico:Historico[]}|null>(null);const[salvando,setSalvando]=useState(false);
  const carregar=useCallback(async()=>{try{setRegistros(await api<Registro[]>());}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível carregar os registros.");}},[]);useEffect(()=>{void carregar();},[carregar]);
  const visiveis=useMemo(()=>registros.filter(r=>(filtro==="TODOS"||r.sacramento===filtro)&&(!busca||`${r.pessoaNome} ${Object.values(r.dadosEspecificos||{}).join(" ")} ${r.livro} ${r.folha} ${r.termo} ${r.numeroRegistro} ${r.maeNome} ${r.paiNome}`.toLowerCase().includes(busca.toLowerCase()))),[registros,busca,filtro]);
  const especifico=(chave:string,valor:string)=>setForm(f=>({...f,dadosEspecificos:{...f.dadosEspecificos,[chave]:valor}}));
  function editar(r:Registro){setForm({id:r.id,sacramento:r.sacramento,pessoaNome:r.pessoaNome,pessoaNascimento:r.pessoaNascimento||"",pessoaNaturalidade:r.pessoaNaturalidade,paiNome:r.paiNome,maeNome:r.maeNome,padrinho1:r.padrinhos[0]||"",padrinho2:r.padrinhos[1]||"",dataSacramento:r.dataSacramento,celebrante:r.celebrante,localSacramento:r.localSacramento,livro:r.livro,folha:r.folha,termo:r.termo,numeroRegistro:r.numeroRegistro,observacoes:r.observacoes,ativo:r.ativo,dadosEspecificos:r.dadosEspecificos||{}});setAberto(true)}
  async function abrirDetalhe(id:string){try{setDetalhe(await api<{registro:Registro;historico:Historico[]}>(`?id=${id}`));}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível abrir o histórico.");}}
  async function salvar(e:FormEvent){e.preventDefault();setSalvando(true);try{const payload={...form,pessoaNascimento:form.pessoaNascimento||null,padrinhos:[form.padrinho1,form.padrinho2].filter(Boolean)};await api("",{method:form.id?"PATCH":"POST",body:JSON.stringify(payload)});toast.success("Registro sacramental salvo.");setAberto(false);setForm(vazio());await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setSalvando(false)}}
  const rotuloPessoa=form.sacramento==="MATRIMONIO"?"Primeiro nubente":form.sacramento==="BATISMO"?"Nome do batizando":form.sacramento==="CRISMA"?"Nome do crismando":"Nome do participante";
  return <main className="min-h-screen bg-slate-100"><ModuleHeader titulo="Registros sacramentais"/><div className="mx-auto max-w-7xl space-y-4 p-4 sm:p-6"><section className="flex flex-col gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={20}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar pessoa, pais, cônjuge, livro ou número" className="min-h-12 w-full rounded-xl border pl-10 pr-3"/></div><select value={filtro} onChange={e=>setFiltro(e.target.value)} className="min-h-12 rounded-xl border bg-white px-3"><option value="TODOS">Todos os sacramentos</option>{Object.entries(nomes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={()=>{setForm(vazio());setAberto(true)}} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 font-black text-white"><Plus size={18}/>Novo registro</button></section><section className="grid gap-3 lg:grid-cols-2">{visiveis.map(r=><article key={r.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${!r.ativo?"opacity-55":""}`}><div className="flex items-start justify-between"><div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{nomes[r.sacramento]}</span><h2 className="mt-3 text-lg font-black">{r.pessoaNome}{r.dadosEspecificos?.conjugeNome&&` e ${r.dadosEspecificos.conjugeNome}`}</h2><p className="text-sm text-slate-500">{new Date(`${r.dataSacramento}T12:00:00`).toLocaleDateString("pt-BR")} • Livro {r.livro}, folha {r.folha}, termo {r.termo}</p><p className="text-sm text-slate-500">Registro nº {r.numeroRegistro}</p></div><BookOpen className="text-blue-200" size={32}/></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>editar(r)} className="inline-flex min-h-11 items-center justify-center gap-1 rounded-xl border font-bold text-blue-700"><Pencil size={17}/>Editar</button><button onClick={()=>void abrirDetalhe(r.id)} className="inline-flex min-h-11 items-center justify-center gap-1 rounded-xl border font-bold"><History size={17}/>Histórico</button><a href={`/secretaria/sacramentos/${r.id}/certidao`} className="inline-flex min-h-11 items-center justify-center gap-1 rounded-xl bg-slate-900 px-2 font-bold text-white"><FileText size={17}/>Certidão</a></div></article>)}{!visiveis.length&&<div className="rounded-2xl bg-white p-10 text-center text-slate-500 lg:col-span-2">Nenhum registro encontrado.</div>}</section></div>
    {aberto&&<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/50 sm:place-items-center"><form onSubmit={salvar} className="max-h-[96vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-3xl sm:rounded-3xl"><h2 className="text-xl font-black">{form.id?"Editar registro":"Novo registro sacramental"}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Sacramento<select value={form.sacramento} onChange={e=>setForm({...vazio(),id:form.id,sacramento:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border bg-white px-3">{Object.entries(nomes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><Campo label="Data do sacramento" type="date" valor={form.dataSacramento} onChange={v=>setForm({...form,dataSacramento:v})} required/><div className="sm:col-span-2"><Campo label={rotuloPessoa} valor={form.pessoaNome} onChange={v=>setForm({...form,pessoaNome:v})} required/></div>
      {form.sacramento==="MATRIMONIO"?<><Campo label="Nascimento do primeiro nubente" type="date" valor={form.pessoaNascimento} onChange={v=>setForm({...form,pessoaNascimento:v})}/><Campo label="Segundo nubente" valor={form.dadosEspecificos.conjugeNome||""} onChange={v=>especifico("conjugeNome",v)} required/><Campo label="Nascimento do segundo nubente" type="date" valor={form.dadosEspecificos.conjugeNascimento||""} onChange={v=>especifico("conjugeNascimento",v)}/><Campo label="Processo matrimonial" valor={form.dadosEspecificos.processoMatrimonial||""} onChange={v=>especifico("processoMatrimonial",v)}/><Campo label="Pai do primeiro nubente" valor={form.paiNome} onChange={v=>setForm({...form,paiNome:v})}/><Campo label="Mãe do primeiro nubente" valor={form.maeNome} onChange={v=>setForm({...form,maeNome:v})}/><Campo label="Pai do segundo nubente" valor={form.dadosEspecificos.conjugePai||""} onChange={v=>especifico("conjugePai",v)}/><Campo label="Mãe do segundo nubente" valor={form.dadosEspecificos.conjugeMae||""} onChange={v=>especifico("conjugeMae",v)}/><Campo label="Testemunha 1" valor={form.padrinho1} onChange={v=>setForm({...form,padrinho1:v})}/><Campo label="Testemunha 2" valor={form.padrinho2} onChange={v=>setForm({...form,padrinho2:v})}/><div className="sm:col-span-2"><Campo label="Dispensas ou observações canônicas" valor={form.dadosEspecificos.dispensas||""} onChange={v=>especifico("dispensas",v)}/></div></>:<><Campo label="Nascimento" type="date" valor={form.pessoaNascimento} onChange={v=>setForm({...form,pessoaNascimento:v})}/><Campo label="Naturalidade" valor={form.pessoaNaturalidade} onChange={v=>setForm({...form,pessoaNaturalidade:v})}/><Campo label="Nome do pai" valor={form.paiNome} onChange={v=>setForm({...form,paiNome:v})}/><Campo label="Nome da mãe" valor={form.maeNome} onChange={v=>setForm({...form,maeNome:v})}/>{form.sacramento==="BATISMO"&&<><Campo label="Padrinho" valor={form.padrinho1} onChange={v=>setForm({...form,padrinho1:v})}/><Campo label="Madrinha" valor={form.padrinho2} onChange={v=>setForm({...form,padrinho2:v})}/></>}{form.sacramento==="CRISMA"&&<><Campo label="Padrinho ou madrinha" valor={form.padrinho1} onChange={v=>setForm({...form,padrinho1:v})}/><Campo label="Turma de preparação" valor={form.dadosEspecificos.turma||""} onChange={v=>especifico("turma",v)}/></>}{["PRIMEIRA_COMUNHAO","CRISMA"].includes(form.sacramento)&&<><Campo label="Data do batismo" type="date" valor={form.dadosEspecificos.dataBatismo||""} onChange={v=>especifico("dataBatismo",v)}/><Campo label="Paróquia do batismo" valor={form.dadosEspecificos.paroquiaBatismo||""} onChange={v=>especifico("paroquiaBatismo",v)} required/></>}{form.sacramento==="PRIMEIRA_COMUNHAO"&&<><Campo label="Catequista" valor={form.dadosEspecificos.catequista||""} onChange={v=>especifico("catequista",v)}/><Campo label="Turma/período da catequese" valor={form.dadosEspecificos.turma||""} onChange={v=>especifico("turma",v)}/></>}</>}
      <Campo label="Celebrante" valor={form.celebrante} onChange={v=>setForm({...form,celebrante:v})}/><Campo label="Local" valor={form.localSacramento} onChange={v=>setForm({...form,localSacramento:v})}/><div className="grid grid-cols-4 gap-2 sm:col-span-2"><Campo label="Livro" valor={form.livro} onChange={v=>setForm({...form,livro:v})} required/><Campo label="Folha" valor={form.folha} onChange={v=>setForm({...form,folha:v})} required/><Campo label="Termo" valor={form.termo} onChange={v=>setForm({...form,termo:v})} required/><Campo label="Número" valor={form.numeroRegistro} onChange={v=>setForm({...form,numeroRegistro:v})} required/></div><label className="text-sm font-bold sm:col-span-2">Observações<textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal"/></label>{form.id&&<label className="flex items-center gap-2 font-bold sm:col-span-2"><input type="checkbox" checked={form.ativo} onChange={e=>setForm({...form,ativo:e.target.checked})}/>Registro ativo</label>}</div><div className="mt-5 flex gap-2"><button disabled={salvando} className="min-h-12 flex-1 rounded-xl bg-blue-600 font-black text-white">{salvando?"Salvando...":"Salvar registro"}</button><button type="button" onClick={()=>setAberto(false)} className="rounded-xl border px-5 font-bold">Cancelar</button></div></form></div>}
    {detalhe&&<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/50 sm:place-items-center"><section className="max-h-[90vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-xl sm:rounded-3xl"><h2 className="text-xl font-black">Histórico de {detalhe.registro.pessoaNome}</h2><div className="mt-4 space-y-4 border-l-2 border-slate-200 pl-4">{detalhe.historico.map(h=><div key={h.id}><p className="font-bold">{h.descricao}</p><p className="text-xs text-slate-500">{h.criadoPorNome} • {new Date(h.createdAt).toLocaleString("pt-BR")}</p></div>)}</div><button onClick={()=>setDetalhe(null)} className="mt-5 min-h-12 w-full rounded-xl border font-bold">Fechar</button></section></div>}
  </main>}
export default function SacramentosPage(){return <ProtectedArea><Conteudo/></ProtectedArea>}
