import { randomUUID } from "node:crypto";
import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
const tipos=["BATISMO","CASAMENTO","PRIMEIRA_COMUNHAO","CRISMA","SEGUNDA_VIA","INTENCAO_MISSA","OUTROS"] as const;
const statuses=["RECEBIDA","EM_ANDAMENTO","AGUARDANDO_DOCUMENTOS","PRONTA","CONCLUIDA","CANCELADA"] as const;
const criar=z.object({tipo:z.enum(tipos),solicitanteNome:z.string().trim().min(3),telefone:z.string().trim().max(20),interessadoNome:z.string().trim().max(120),prazo:z.string().nullable(),observacoes:z.string().trim().max(1000),valor:z.number().min(0)});
const alterar=z.discriminatedUnion("acao",[z.object({acao:z.literal("STATUS"),id:z.uuid(),status:z.enum(statuses),observacao:z.string().trim().max(300)}),z.object({acao:z.literal("PAGAR"),id:z.uuid(),contaId:z.uuid()})]);
const permitidos=["admin_plataforma","admin_paroquia","atendente_secretaria"];
function erro(e:unknown){const original=e instanceof Error?e.message:e&&typeof e==="object"&&"message" in e?String(e.message):"Erro interno.";return NextResponse.json({erro:original},{status:original==="UNAUTHENTICATED"?401:original==="FORBIDDEN"?403:400});}
function protocolo(){return `SEC-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${randomUUID().slice(0,6).toUpperCase()}`;}
function documentos(tipo:typeof tipos[number]){const listas:Partial<Record<typeof tipos[number],string[]>>={BATISMO:["Certidão de nascimento","Documento dos pais","Documento dos padrinhos","Comprovante do curso de batismo"],CASAMENTO:["Certidão de batismo atualizada","Documentos dos noivos","Comprovante de residência","Comprovante do curso de noivos"],PRIMEIRA_COMUNHAO:["Certidão de batismo","Comprovante da catequese"],CRISMA:["Certidão de batismo","Comprovante da catequese","Documento do padrinho ou madrinha"],SEGUNDA_VIA:["Documento de identificação","Dados para localização do registro"]};return(listas[tipo]??[]).map(nome=>({id:randomUUID(),nome,entregue:false}));}
export async function GET(req:NextRequest){try{const usuario=await exigirUsuarioAtivo(req);if(!permitidos.includes(usuario.role))throw new Error("FORBIDDEN");const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,usuario);const[lista,contas]=await Promise.all([supabase.from("secretaria_solicitacoes").select("*").eq("paroquia_id",paroquiaId).order("created_at",{ascending:false}).limit(300),supabase.from("tesouraria_contas").select("id,nome,tipo").eq("paroquia_id",paroquiaId).eq("ativa",true).order("nome")]);if(lista.error)throw lista.error;if(contas.error)throw contas.error;return NextResponse.json({solicitacoes:(lista.data??[]).map(i=>({id:i.id,protocolo:i.protocolo,tipo:i.tipo,solicitanteNome:i.solicitante_nome,telefone:i.telefone,interessadoNome:i.interessado_nome,prazo:i.prazo,observacoes:i.observacoes,status:i.status,valor:Number(i.valor),pago:i.pago,pagoEm:i.pago_em,criadoPorNome:i.criado_por_nome,createdAt:i.created_at})),contas:contas.data??[]});}catch(e){return erro(e)}}
export async function POST(req:NextRequest){try{const usuario=await exigirUsuarioAtivo(req);if(!permitidos.includes(usuario.role))throw new Error("FORBIDDEN");const d=criar.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,usuario);const registro=await supabase.from("secretaria_solicitacoes").insert({paroquia_id:paroquiaId,protocolo:protocolo(),tipo:d.tipo,solicitante_nome:d.solicitanteNome,telefone:d.telefone,interessado_nome:d.interessadoNome,prazo:d.prazo||null,observacoes:d.observacoes,valor:d.valor,documentos_checklist:documentos(d.tipo),criado_por:usuario.uid,criado_por_nome:usuario.nome}).select("id,protocolo").single();if(registro.error)throw registro.error;await supabase.from("secretaria_solicitacoes_historico").insert({paroquia_id:paroquiaId,solicitacao_id:registro.data.id,status:"RECEBIDA",observacao:"Solicitação recebida",criado_por:usuario.uid,criado_por_nome:usuario.nome});return NextResponse.json(registro.data,{status:201});}catch(e){return erro(e)}}
export async function PATCH(req:NextRequest){try{const usuario=await exigirUsuarioAtivo(req);if(!permitidos.includes(usuario.role))throw new Error("FORBIDDEN");const d=alterar.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,usuario);if(d.acao==="PAGAR"){const pagamento=await supabase.rpc("registrar_pagamento_solicitacao_secretaria",{p_paroquia_id:paroquiaId,p_solicitacao_id:d.id,p_conta_id:d.contaId,p_criado_por:usuario.uid});if(pagamento.error)throw pagamento.error;return NextResponse.json({id:d.id});}const atualizacao=await supabase.from("secretaria_solicitacoes").update({status:d.status,updated_at:new Date().toISOString()}).eq("id",d.id).eq("paroquia_id",paroquiaId);if(atualizacao.error)throw atualizacao.error;const historico=await supabase.from("secretaria_solicitacoes_historico").insert({paroquia_id:paroquiaId,solicitacao_id:d.id,status:d.status,observacao:d.observacao,criado_por:usuario.uid,criado_por_nome:usuario.nome});if(historico.error)throw historico.error;return NextResponse.json({id:d.id});}catch(e){return erro(e)}}
