"use client";
import { Building2, KeyRound, LogOut, Plus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { sair } from "@/lib/firebase/auth";
import { useAuth } from "@/modules/auth/hooks/useAuth";
import { useParoquia } from "@/modules/paroquias/hooks/useParoquia";
import { ParoquiaDocumento } from "@/modules/paroquias/types/paroquia-documento";

export default function CentralPage() {
  const router = useRouter(); const { usuario, carregando } = useAuth(); const { listar, selecionar } = useParoquia(false); const [paroquias, setParoquias] = useState<ParoquiaDocumento[]>([]); const [abrindo, setAbrindo] = useState("");
  useEffect(() => { if (!carregando && !usuario) router.replace("/login"); else if (!carregando && usuario?.role !== "admin_plataforma") router.replace("/dashboard"); }, [carregando, router, usuario]);
  useEffect(() => { if (usuario?.role === "admin_plataforma") listar().then(setParoquias).catch(() => toast.error("Não foi possível carregar as paróquias.")); }, [listar, usuario]);
  async function entrar(item: ParoquiaDocumento) { setAbrindo(item.id); try { await selecionar(item.id); router.push("/dashboard"); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível acessar a paróquia."); setAbrindo(""); } }
  if (carregando || usuario?.role !== "admin_plataforma") return <div className="flex min-h-screen items-center justify-center bg-slate-100 text-slate-500">Verificando acesso...</div>;
  return <main className="min-h-screen bg-slate-100"><header className="border-b bg-white px-8 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><h1 className="text-2xl font-bold text-blue-700">Central de Administração</h1><p className="text-sm text-slate-500">Ágape Social — Gestão da plataforma</p></div><button onClick={() => void sair().then(() => router.replace("/login"))} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-slate-700"><LogOut size={18} /> Sair</button></div></header><div className="mx-auto max-w-7xl space-y-6 p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Selecione uma paróquia</h2><p className="mt-1 text-slate-500">Entre no ambiente pastoral da unidade que deseja administrar.</p></div><div className="flex flex-wrap gap-3"><Link href="/central/administradores" className="inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-white px-4 py-3 font-semibold text-blue-700"><KeyRound size={18} /> Administrar logins</Link><Link href="/paroquias/nova" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white"><Plus size={18} /> Nova paróquia</Link></div></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{paroquias.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><Building2 /></div><div><h3 className="font-semibold text-slate-900">{item.nome}</h3><p className="mt-1 text-sm text-slate-500">{item.cidade}/{item.estado}</p><span className={`mt-3 inline-block rounded-full px-2.5 py-1 text-xs font-semibold ${item.ativa ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{item.ativa ? "Ativa" : "Inativa"}</span></div></div><button type="button" disabled={!item.ativa || Boolean(abrindo)} onClick={() => entrar(item)} className="mt-6 w-full rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-50">{abrindo === item.id ? "Abrindo..." : "Acessar Ágape Social"}</button></article>)}</div><div className="border-t pt-5"><Link href="/paroquias" className="font-medium text-blue-700">Gerenciar cadastro e status das paróquias</Link></div></div></main>;
}
