"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowDownCircle, ArrowUpCircle, Building2, LayoutDashboard, ListTree, LogOut, Plus, WalletCards } from "lucide-react";
import toast from "react-hot-toast";
import { ProtectedArea } from "@/components/auth/ProtectedArea";
import { obterTokenAcesso, sair } from "@/lib/auth/client-session";
import { ResumoTesouraria } from "@/modules/tesouraria/types";
const moeda=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
async function api<T>(init?:RequestInit){const token=await obterTokenAcesso();const resposta=await fetch("/api/tesouraria",{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const dados=await resposta.json();if(!resposta.ok)throw new Error(dados.erro||"Operação não concluída.");return dados as T;}
const vazio:ResumoTesouraria={saldoTotal:0,entradasMes:0,saidasMes:0,resultadoMes:0,contas:[],categorias:[],movimentacoes:[]};
function Conteudo(){const [dados,setDados]=useState(vazio);const [aba,setAba]=useState<"DASH"|"FLUXO"|"CONTAS"|"CATEGORIAS">("DASH");const [tipoMov,setTipoMov]=useState<"ENTRADA"|"SAIDA">("ENTRADA");const [mov,setMov]=useState({contaId:"",categoriaId:"",valor:"",data:new Date().toISOString().slice(0,10),descricao:""});const [conta,setConta]=useState({nome:"",tipo:"CAIXA",banco:"",agencia:"",numeroConta:"",saldoInicial:"0"});const [categoria,setCategoria]=useState({nome:"",natureza:"RECEITA"});
const carregar=useCallback(async()=>{try{setDados(await api<ResumoTesouraria>());}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível carregar a Tesouraria.");}},[]);useEffect(()=>{void carregar();},[carregar]);
async function salvarMov(e:FormEvent){e.preventDefault();try{await api({method:"POST",body:JSON.stringify({entidade:"MOVIMENTACAO",...mov,tipo:tipoMov,valor:Number(mov.valor.replace(",","."))})});toast.success("Lançamento registrado.");setMov({...mov,valor:"",descricao:""});await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível lançar.");}}
async function salvarConta(e:FormEvent){e.preventDefault();try{await api({method:"POST",body:JSON.stringify({entidade:"CONTA",...conta,saldoInicial:Number(conta.saldoInicial.replace(",","."))})});toast.success("Conta cadastrada.");setConta({nome:"",tipo:"CAIXA",banco:"",agencia:"",numeroConta:"",saldoInicial:"0"});await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível cadastrar.");}}
async function salvarCategoria(e:FormEvent){e.preventDefault();try{await api({method:"POST",body:JSON.stringify({entidade:"CATEGORIA",...categoria})});toast.success("Categoria cadastrada.");setCategoria({nome:"",natureza:"RECEITA"});await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível cadastrar.");}}
const categoriasFiltradas=dados.categorias.filter(c=>c.ativa&&c.natureza===(tipoMov==="ENTRADA"?"RECEITA":"DESPESA"));
return <main className="min-h-screen bg-slate-100"><header className="sticky top-0 z-20 border-b bg-white px-4 py-3"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-emerald-600">Ágape</p><h1 className="text-xl font-black">Tesouraria</h1></div><button onClick={()=>void sair().then(()=>location.assign("/login"))} className="rounded-xl border p-3" aria-label="Sair"><LogOut size={20}/></button></div></header><div className="mx-auto max-w-7xl p-4 sm:p-6"><nav className="mb-6 grid grid-cols-4 gap-2 rounded-2xl bg-white p-2 shadow-sm">{([["DASH","Painel",LayoutDashboard],["FLUXO","Fluxo",WalletCards],["CONTAS","Contas",Building2],["CATEGORIAS","Categorias",ListTree]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setAba(id)} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-xs font-bold sm:flex-row sm:text-sm ${aba===id?"bg-emerald-600 text-white":"text-slate-600"}`}><Icon size={19}/>{label}</button>)}</nav>
{aba==="DASH"&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Saldo total",dados.saldoTotal,"bg-slate-900"],["Entradas no mês",dados.entradasMes,"bg-emerald-600"],["Saídas no mês",dados.saidasMes,"bg-red-600"],["Resultado do mês",dados.resultadoMes,dados.resultadoMes>=0?"bg-blue-600":"bg-amber-600"]].map(([titulo,valor,cor])=><article key={String(titulo)} className={`${cor} rounded-2xl p-5 text-white shadow-sm`}><p className="text-sm opacity-80">{titulo}</p><p className="mt-2 text-3xl font-black">{moeda(Number(valor))}</p></article>)}</section><section className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{dados.contas.filter(c=>c.ativa).map(c=><article key={c.id} className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-700"><Building2/></div><div><h2 className="font-bold">{c.nome}</h2><p className="text-xs text-slate-500">{c.tipo.replace("_"," ")}</p></div></div><p className="mt-4 text-2xl font-black">{moeda(c.saldo)}</p></article>)}</section></>}
{aba==="FLUXO"&&<div className="grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={salvarMov} className="h-fit space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Novo lançamento</h2><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setTipoMov("ENTRADA");setMov({...mov,categoriaId:""});}} className={`min-h-12 rounded-xl font-bold ${tipoMov==="ENTRADA"?"bg-emerald-600 text-white":"bg-slate-100"}`}>Entrada</button><button type="button" onClick={()=>{setTipoMov("SAIDA");setMov({...mov,categoriaId:""});}} className={`min-h-12 rounded-xl font-bold ${tipoMov==="SAIDA"?"bg-red-600 text-white":"bg-slate-100"}`}>Saída</button></div><select value={mov.contaId} onChange={e=>setMov({...mov,contaId:e.target.value})} className="min-h-12 w-full rounded-xl border bg-white px-3" required><option value="">Selecione a conta</option>{dados.contas.filter(c=>c.ativa).map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select><select value={mov.categoriaId} onChange={e=>setMov({...mov,categoriaId:e.target.value})} className="min-h-12 w-full rounded-xl border bg-white px-3" required><option value="">Selecione a categoria</option>{categoriasFiltradas.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select><input inputMode="decimal" value={mov.valor} onChange={e=>setMov({...mov,valor:e.target.value})} placeholder="Valor" className="min-h-12 w-full rounded-xl border px-4" required/><input type="date" value={mov.data} onChange={e=>setMov({...mov,data:e.target.value})} className="min-h-12 w-full rounded-xl border px-4" required/><input value={mov.descricao} onChange={e=>setMov({...mov,descricao:e.target.value})} placeholder="Descrição" className="min-h-12 w-full rounded-xl border px-4" required/><button className={`min-h-12 w-full rounded-xl font-bold text-white ${tipoMov==="ENTRADA"?"bg-emerald-600":"bg-red-600"}`}>Registrar {tipoMov==="ENTRADA"?"entrada":"saída"}</button></form><section className="space-y-2">{dados.movimentacoes.map(m=><article key={m.id} className="flex items-center justify-between gap-3 rounded-xl border bg-white p-4"><div className="flex items-center gap-3">{m.tipo==="ENTRADA"?<ArrowUpCircle className="text-emerald-600"/>:<ArrowDownCircle className="text-red-600"/>}<div><p className="font-bold">{m.descricao}</p><p className="text-xs text-slate-500">{new Date(`${m.data}T12:00:00`).toLocaleDateString("pt-BR")} • {m.contaNome} • {m.categoriaNome}</p></div></div><strong className={m.tipo==="ENTRADA"?"text-emerald-700":"text-red-700"}>{m.tipo==="ENTRADA"?"+":"-"}{moeda(m.valor)}</strong></article>)}</section></div>}
{aba==="CONTAS"&&<div className="grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={salvarConta} className="h-fit space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Nova conta</h2><input value={conta.nome} onChange={e=>setConta({...conta,nome:e.target.value})} placeholder="Nome da conta" className="min-h-12 w-full rounded-xl border px-4" required/><select value={conta.tipo} onChange={e=>setConta({...conta,tipo:e.target.value})} className="min-h-12 w-full rounded-xl border bg-white px-3"><option value="CAIXA">Caixa</option><option value="BANCO">Banco</option><option value="CONTA_PAGAMENTO">Conta de pagamento</option></select>{conta.tipo!=="CAIXA"&&<><input value={conta.banco} onChange={e=>setConta({...conta,banco:e.target.value})} placeholder="Banco" className="min-h-12 w-full rounded-xl border px-4"/><div className="grid grid-cols-2 gap-2"><input value={conta.agencia} onChange={e=>setConta({...conta,agencia:e.target.value})} placeholder="Agência" className="min-h-12 w-full rounded-xl border px-4"/><input value={conta.numeroConta} onChange={e=>setConta({...conta,numeroConta:e.target.value})} placeholder="Conta" className="min-h-12 w-full rounded-xl border px-4"/></div></>}<input inputMode="decimal" value={conta.saldoInicial} onChange={e=>setConta({...conta,saldoInicial:e.target.value})} placeholder="Saldo inicial" className="min-h-12 w-full rounded-xl border px-4"/><button className="min-h-12 w-full rounded-xl bg-emerald-600 font-bold text-white"><Plus className="mr-1 inline" size={18}/>Cadastrar conta</button></form><section className="space-y-2">{dados.contas.map(c=><article key={c.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between"><div><strong>{c.nome}</strong><p className="text-sm text-slate-500">{c.banco||c.tipo.replace("_"," ")} {c.numeroConta&&`• ${c.numeroConta}`}</p></div><strong>{moeda(c.saldo)}</strong></div></article>)}</section></div>}
{aba==="CATEGORIAS"&&<div className="grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={salvarCategoria} className="h-fit space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Nova categoria</h2><input value={categoria.nome} onChange={e=>setCategoria({...categoria,nome:e.target.value})} placeholder="Nome da categoria" className="min-h-12 w-full rounded-xl border px-4" required/><select value={categoria.natureza} onChange={e=>setCategoria({...categoria,natureza:e.target.value})} className="min-h-12 w-full rounded-xl border bg-white px-3"><option value="RECEITA">Receita</option><option value="DESPESA">Despesa</option></select><button className="min-h-12 w-full rounded-xl bg-emerald-600 font-bold text-white">Cadastrar categoria</button></form><section className="grid gap-2 sm:grid-cols-2">{dados.categorias.map(c=><article key={c.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><strong>{c.nome}</strong><span className={`rounded-full px-2 py-1 text-xs font-bold ${c.natureza==="RECEITA"?"bg-emerald-100 text-emerald-700":"bg-red-100 text-red-700"}`}>{c.natureza}</span></article>)}</section></div>}
</div></main>}
export default function TesourariaPage(){return <ProtectedArea><Conteudo/></ProtectedArea>}
