import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";
const sacramentos=["BATISMO","PRIMEIRA_COMUNHAO","CRISMA","MATRIMONIO"] as const;
const base=z.object({sacramento:z.enum(sacramentos),pessoaNome:z.string().trim().min(3).max(150),pessoaNascimento:z.string().nullable(),pessoaNaturalidade:z.string().trim().max(120),paiNome:z.string().trim().max(150),maeNome:z.string().trim().max(150),padrinhos:z.array(z.string().trim().min(2).max(150)).max(4),dadosEspecificos:z.record(z.string(),z.string().max(300)).default({}),dataSacramento:z.string().min(10).max(10),celebrante:z.string().trim().max(150),localSacramento:z.string().trim().max(150),livro:z.string().trim().min(1).max(30),folha:z.string().trim().min(1).max(30),termo:z.string().trim().min(1).max(30),numeroRegistro:z.string().trim().min(1).max(50),observacoes:z.string().trim().max(1000),ativo:z.boolean().default(true)}).superRefine((d,c)=>{if(d.sacramento==="MATRIMONIO"&&!d.dadosEspecificos.conjugeNome)c.addIssue({code:"custom",path:["dadosEspecificos","conjugeNome"],message:"Informe o nome do segundo nubente."});if(["PRIMEIRA_COMUNHAO","CRISMA"].includes(d.sacramento)&&!d.dadosEspecificos.paroquiaBatismo)c.addIssue({code:"custom",path:["dadosEspecificos","paroquiaBatismo"],message:"Informe a paróquia do batismo."});});const editar=base.and(z.object({id:z.uuid()}));
const permitidos=["admin_plataforma","admin_paroquia","atendente_secretaria"];
const map=(i:Record<string,unknown>)=>({id:i.id,sacramento:i.sacramento,pessoaNome:i.pessoa_nome,pessoaNascimento:i.pessoa_nascimento,pessoaNaturalidade:i.pessoa_naturalidade,paiNome:i.pai_nome,maeNome:i.mae_nome,padrinhos:i.padrinhos??[],dadosEspecificos:i.dados_especificos??{},dataSacramento:i.data_sacramento,celebrante:i.celebrante,localSacramento:i.local_sacramento,livro:i.livro,folha:i.folha,termo:i.termo,numeroRegistro:i.numero_registro,observacoes:i.observacoes,ativo:i.ativo,criadoPorNome:i.criado_por_nome,createdAt:i.created_at});
function erro(e:unknown){const m=e instanceof Error?e.message:e&&typeof e==="object"&&"message" in e?String(e.message):"Erro interno.";return NextResponse.json({erro:/duplicate|unique/i.test(m)?"Já existe um registro com este sacramento, livro e número.":m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:400});}
const banco=(d:z.infer<typeof base>)=>({sacramento:d.sacramento,pessoa_nome:d.pessoaNome,pessoa_nascimento:d.pessoaNascimento||null,pessoa_naturalidade:d.pessoaNaturalidade,pai_nome:d.paiNome,mae_nome:d.maeNome,padrinhos:d.padrinhos,dados_especificos:d.dadosEspecificos,data_sacramento:d.dataSacramento,celebrante:d.celebrante,local_sacramento:d.localSacramento,livro:d.livro,folha:d.folha,termo:d.termo,numero_registro:d.numeroRegistro,observacoes:d.observacoes,ativo:d.ativo,updated_at:new Date().toISOString()});
export async function GET(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const id=req.nextUrl.searchParams.get("id");if(id){const[registro,historico]=await Promise.all([supabase.from("secretaria_registros_sacramentais").select("*").eq("id",id).eq("paroquia_id",paroquiaId).single(),supabase.from("secretaria_registros_sacramentais_historico").select("*").eq("registro_id",id).eq("paroquia_id",paroquiaId).order("created_at",{ascending:false})]);if(registro.error)throw registro.error;if(historico.error)throw historico.error;return NextResponse.json({registro:map(registro.data),historico:(historico.data??[]).map(h=>({id:h.id,acao:h.acao,descricao:h.descricao,criadoPorNome:h.criado_por_nome,createdAt:h.created_at}))});}const{data,error}=await supabase.from("secretaria_registros_sacramentais").select("*").eq("paroquia_id",paroquiaId).order("data_sacramento",{ascending:false}).limit(500);if(error)throw error;return NextResponse.json((data??[]).map(i=>map(i)));}catch(e){return erro(e)}}
export async function POST(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const d=base.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_registros_sacramentais").insert({paroquia_id:paroquiaId,...banco(d),criado_por:u.uid,criado_por_nome:u.nome}).select("*").single();if(error)throw error;await supabase.from("secretaria_registros_sacramentais_historico").insert({paroquia_id:paroquiaId,registro_id:data.id,acao:"CRIACAO",descricao:"Registro sacramental criado",criado_por:u.uid,criado_por_nome:u.nome});return NextResponse.json(map(data),{status:201});}catch(e){return erro(e)}}
export async function PATCH(req:NextRequest){try{const u=await exigirUsuarioAtivo(req);if(!permitidos.includes(u.role))throw new Error("FORBIDDEN");const d=editar.parse(await req.json());const{supabase,paroquiaId}=await resolverParoquiaDaRequisicao(req,u);const{data,error}=await supabase.from("secretaria_registros_sacramentais").update(banco(d)).eq("id",d.id).eq("paroquia_id",paroquiaId).select("*").single();if(error)throw error;await supabase.from("secretaria_registros_sacramentais_historico").insert({paroquia_id:paroquiaId,registro_id:d.id,acao:d.ativo?"ALTERACAO":"INATIVACAO",descricao:d.ativo?"Dados do registro atualizados":"Registro sacramental inativado",criado_por:u.uid,criado_por_nome:u.nome});return NextResponse.json(map(data));}catch(e){return erro(e)}}
