"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { CalendarDays, HeartHandshake, Plus, RefreshCw, Users } from "lucide-react";
import toast from "react-hot-toast";
import { PageHeader } from "@/components/ui/PageHeader";
import { useEcc } from "@/modules/ecc/hooks/useEcc";
import type { EccCasalFormData, EccEncontroFormData, EccEquipeFormData } from "@/modules/ecc/schemas/ecc.schema";
import type { EccPainel } from "@/modules/ecc/types/ecc.types";

const vazio:EccPainel={encontros:[],casais:[],equipe:[],voluntarios:[]};
const hoje=new Date().toISOString().slice(0,10);
const encontroInicial:EccEncontroFormData={numero:1,nome:"Encontro de Casais com Cristo",tema:"",lema:"",dataInicio:hoje,dataFim:hoje,prazoInscricao:"",local:"",capacidadeCasais:0,status:"PLANEJAMENTO",observacoes:""};
const casalInicial:EccCasalFormData={conjugeUmNome:"",conjugeDoisNome:"",telefone:"",email:"",dataCasamento:"",encontroId:"",voluntarioUmId:"",voluntarioDoisId:"",situacao:"ELEGIVEL",observacoes:""};
const equipeInicial:EccEquipeFormData={encontroId:"",voluntarioId:"",equipe:"",funcao:"Voluntário",coordenador:false,status:"CONVIDADO",observacoes:""};

const campo="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const label="grid gap-1 text-sm font-semibold text-slate-700";
const statusEncontro:Record<string,string>={PLANEJAMENTO:"Planejamento",INSCRICOES:"Inscrições",PREPARACAO:"Preparação",REALIZADO:"Realizado",ENCERRADO:"Encerrado"};
const statusCasal:Record<string,string>={ELEGIVEL:"Elegível",CONVIDADO:"Convidado",INSCRITO:"Inscrito",CONFIRMADO:"Confirmado",LISTA_ESPERA:"Lista de espera",DESISTENTE:"Desistente",PARTICIPOU:"Participou"};

function CartaoMetrica({icone:Icon,rotulo,valor,apoio}:{icone:typeof Users;rotulo:string;valor:number;apoio:string}){return <article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon size={22}/></span><div><p className="text-xs font-black uppercase tracking-[.12em] text-slate-500">{rotulo}</p><strong className="text-3xl text-slate-900">{valor}</strong></div></div><p className="mt-3 text-sm text-slate-500">{apoio}</p></article>}

export default function EccPage(){
  const {listar,criarEncontro,criarCasal,adicionarEquipe}=useEcc();
  const [dados,setDados]=useState(vazio);const [carregando,setCarregando]=useState(true);const [salvando,setSalvando]=useState("");
  const [mostrar,setMostrar]=useState<"encontro"|"casal"|"equipe"|null>(null);
  const [encontro,setEncontro]=useState(encontroInicial);const [casal,setCasal]=useState(casalInicial);const [equipe,setEquipe]=useState(equipeInicial);
  const carregar=useCallback(async()=>{setCarregando(true);try{const resposta=await listar();setDados(resposta);setCasal(atual=>({...atual,encontroId:atual.encontroId||resposta.encontros[0]?.id||""}));setEquipe(atual=>({...atual,encontroId:atual.encontroId||resposta.encontros[0]?.id||""}));}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível carregar o ECC.");}finally{setCarregando(false);}},[listar]);
  useEffect(()=>{void carregar();},[carregar]);
  const edicaoAtual=useMemo(()=>dados.encontros.find(item=>!["REALIZADO","ENCERRADO"].includes(item.status))??dados.encontros[0],[dados.encontros]);
  async function executar(tipo:string,acao:()=>Promise<unknown>,limpar:()=>void){setSalvando(tipo);try{await acao();toast.success("Registro do ECC salvo com sucesso.");limpar();setMostrar(null);await carregar();}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar.");}finally{setSalvando("");}}
  function salvarEncontro(event:FormEvent){event.preventDefault();void executar("encontro",()=>criarEncontro(encontro),()=>setEncontro({...encontroInicial,numero:(dados.encontros[0]?.numero??0)+1}));}
  function salvarCasal(event:FormEvent){event.preventDefault();void executar("casal",()=>criarCasal(casal),()=>setCasal({...casalInicial,encontroId:edicaoAtual?.id??""}));}
  function salvarEquipe(event:FormEvent){event.preventDefault();void executar("equipe",()=>adicionarEquipe(equipe),()=>setEquipe({...equipeInicial,encontroId:edicaoAtual?.id??""}));}
  return <main className="mx-auto max-w-7xl space-y-6">
    <PageHeader title="ECC" description="Planeje o Encontro de Casais com Cristo, acompanhe os casais e forme as equipes sem duplicar cadastros." actions={<button type="button" onClick={()=>void carregar()} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50"><RefreshCw size={17}/>Atualizar</button>}/>
    <section className="rounded-2xl bg-gradient-to-r from-blue-800 to-blue-600 p-6 text-white shadow-lg"><p className="text-xs font-black tracking-[.18em] text-blue-100">ENCONTRO DE CASAIS COM CRISTO</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h2 className="text-2xl font-black">{edicaoAtual?`${edicaoAtual.numero}º ECC · ${edicaoAtual.nome}`:"Comece cadastrando a próxima edição"}</h2><p className="mt-2 text-sm text-blue-100">{edicaoAtual?`${edicaoAtual.tema||"Tema ainda não informado"} · ${statusEncontro[edicaoAtual.status]}`:"A estrutura está pronta para organizar inscrições e equipes."}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setMostrar("encontro")} className="rounded-xl bg-white px-4 py-2.5 text-sm font-black text-blue-700"><Plus size={16} className="mr-2 inline"/>Nova edição</button><button onClick={()=>setMostrar("casal")} className="rounded-xl border border-white/40 px-4 py-2.5 text-sm font-black"><Plus size={16} className="mr-2 inline"/>Cadastrar casal</button><button onClick={()=>setMostrar("equipe")} className="rounded-xl border border-white/40 px-4 py-2.5 text-sm font-black"><Plus size={16} className="mr-2 inline"/>Montar equipe</button></div></div></section>
    <section className="grid gap-4 md:grid-cols-3"><CartaoMetrica icone={CalendarDays} rotulo="Edições" valor={dados.encontros.length} apoio="Histórico e encontros em preparação"/><CartaoMetrica icone={Users} rotulo="Casais" valor={dados.casais.length} apoio={`${dados.casais.filter(item=>item.situacao==="CONFIRMADO").length} confirmado(s)`}/><CartaoMetrica icone={HeartHandshake} rotulo="Equipe" valor={dados.equipe.length} apoio={`${dados.voluntarios.length} voluntário(s) disponíveis`}/></section>
    {mostrar&&<section className="rounded-2xl border border-blue-200 bg-blue-50/60 p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-black tracking-[.15em] text-blue-600">NOVO REGISTRO</p><h2 className="mt-1 text-xl font-bold text-slate-900">{mostrar==="encontro"?"Edição do ECC":mostrar==="casal"?"Casal elegível ou participante":"Voluntário na equipe"}</h2></div><button type="button" onClick={()=>setMostrar(null)} className="rounded-lg px-3 py-2 text-sm font-bold text-slate-600">Fechar</button></div>
      {mostrar==="encontro"&&<form onSubmit={salvarEncontro} className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className={label}>Número<input className={campo} type="number" min="1" value={encontro.numero} onChange={e=>setEncontro({...encontro,numero:Number(e.target.value)})}/></label><label className={`${label} lg:col-span-2`}>Nome<input className={campo} value={encontro.nome} onChange={e=>setEncontro({...encontro,nome:e.target.value})}/></label><label className={label}>Situação<select className={campo} value={encontro.status} onChange={e=>setEncontro({...encontro,status:e.target.value as EccEncontroFormData["status"]})}>{Object.entries(statusEncontro).map(([valor,nome])=><option key={valor} value={valor}>{nome}</option>)}</select></label><label className={`${label} md:col-span-2`}>Tema<input className={campo} value={encontro.tema} onChange={e=>setEncontro({...encontro,tema:e.target.value})}/></label><label className={`${label} md:col-span-2`}>Lema<input className={campo} value={encontro.lema} onChange={e=>setEncontro({...encontro,lema:e.target.value})}/></label><label className={label}>Início<input className={campo} type="date" value={encontro.dataInicio} onChange={e=>setEncontro({...encontro,dataInicio:e.target.value})}/></label><label className={label}>Término<input className={campo} type="date" value={encontro.dataFim} onChange={e=>setEncontro({...encontro,dataFim:e.target.value})}/></label><label className={label}>Prazo de inscrição<input className={campo} type="date" value={encontro.prazoInscricao} onChange={e=>setEncontro({...encontro,prazoInscricao:e.target.value})}/></label><label className={label}>Capacidade de casais<input className={campo} type="number" min="0" value={encontro.capacidadeCasais} onChange={e=>setEncontro({...encontro,capacidadeCasais:Number(e.target.value)})}/></label><label className={`${label} md:col-span-2 lg:col-span-3`}>Local<input className={campo} value={encontro.local} onChange={e=>setEncontro({...encontro,local:e.target.value})}/></label><button disabled={salvando==="encontro"} className="self-end rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-60">{salvando==="encontro"?"Salvando...":"Criar edição"}</button></form>}
      {mostrar==="casal"&&<form onSubmit={salvarCasal} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><label className={label}>Primeiro cônjuge<input className={campo} value={casal.conjugeUmNome} onChange={e=>setCasal({...casal,conjugeUmNome:e.target.value})}/></label><label className={label}>Segundo cônjuge<input className={campo} value={casal.conjugeDoisNome} onChange={e=>setCasal({...casal,conjugeDoisNome:e.target.value})}/></label><label className={label}>Situação<select className={campo} value={casal.situacao} onChange={e=>setCasal({...casal,situacao:e.target.value as EccCasalFormData["situacao"]})}>{Object.entries(statusCasal).map(([valor,nome])=><option key={valor} value={valor}>{nome}</option>)}</select></label><label className={label}>Telefone<input className={campo} value={casal.telefone} onChange={e=>setCasal({...casal,telefone:e.target.value})}/></label><label className={label}>E-mail<input className={campo} type="email" value={casal.email} onChange={e=>setCasal({...casal,email:e.target.value})}/></label><label className={label}>Data do casamento<input className={campo} type="date" value={casal.dataCasamento} onChange={e=>setCasal({...casal,dataCasamento:e.target.value})}/></label><label className={`${label} md:col-span-2`}>Vincular à edição (opcional)<select className={campo} value={casal.encontroId} onChange={e=>setCasal({...casal,encontroId:e.target.value})}><option value="">Banco de casais do ECC</option>{dados.encontros.map(item=><option key={item.id} value={item.id}>{item.numero}º ECC · {item.nome}</option>)}</select></label><button disabled={salvando==="casal"} className="self-end rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-60">{salvando==="casal"?"Salvando...":"Cadastrar casal"}</button></form>}
      {mostrar==="equipe"&&<form onSubmit={salvarEquipe} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><label className={label}>Edição<select required className={campo} value={equipe.encontroId} onChange={e=>setEquipe({...equipe,encontroId:e.target.value})}><option value="">Selecione</option>{dados.encontros.map(item=><option key={item.id} value={item.id}>{item.numero}º ECC · {item.nome}</option>)}</select></label><label className={label}>Voluntário<select required className={campo} value={equipe.voluntarioId} onChange={e=>setEquipe({...equipe,voluntarioId:e.target.value})}><option value="">Selecione</option>{dados.voluntarios.map(item=><option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label className={label}>Equipe<input className={campo} placeholder="Ex.: Acolhida, Cozinha, Liturgia" value={equipe.equipe} onChange={e=>setEquipe({...equipe,equipe:e.target.value})}/></label><label className={label}>Função<input className={campo} value={equipe.funcao} onChange={e=>setEquipe({...equipe,funcao:e.target.value})}/></label><label className={`${label} content-center`}><span className="mt-5 flex items-center gap-3"><input type="checkbox" checked={equipe.coordenador} onChange={e=>setEquipe({...equipe,coordenador:e.target.checked})} className="h-5 w-5 accent-blue-600"/>Coordena esta equipe</span></label><button disabled={salvando==="equipe"} className="self-end rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-60">{salvando==="equipe"?"Salvando...":"Adicionar à equipe"}</button></form>}
    </section>}
    <section className="grid items-start gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-900">Edições do encontro</h2><p className="mt-1 text-sm text-slate-500">Planejamento e histórico por paróquia.</p><div className="mt-5 grid gap-3">{carregando?<p className="py-8 text-center text-slate-500">Carregando...</p>:dados.encontros.length===0?<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Nenhuma edição cadastrada.</p>:dados.encontros.map(item=><article key={item.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><strong className="text-slate-900">{item.numero}º ECC · {item.nome}</strong><p className="mt-1 text-sm text-slate-500">{new Date(`${item.dataInicio}T12:00:00`).toLocaleDateString("pt-BR")} a {new Date(`${item.dataFim}T12:00:00`).toLocaleDateString("pt-BR")} {item.local&&`· ${item.local}`}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{statusEncontro[item.status]}</span></div>{item.tema&&<p className="mt-3 text-sm text-slate-700"><b>Tema:</b> {item.tema}</p>}</article>)}</div></div>
      <div className="grid gap-5"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-900">Casais do ECC</h2><p className="mt-1 text-sm text-slate-500">Banco de casais elegíveis, convidados e participantes.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-150 text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wide text-slate-500"><th className="py-3">Casal</th><th>Contato</th><th>Situação</th></tr></thead><tbody>{dados.casais.map(item=><tr key={item.id} className="border-b last:border-0"><td className="py-3 font-semibold text-slate-800">{item.conjugeUmNome} e {item.conjugeDoisNome}</td><td className="text-slate-500">{item.telefone||item.email||"Não informado"}</td><td><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{statusCasal[item.situacao]}</span></td></tr>)}</tbody></table>{!dados.casais.length&&<p className="py-8 text-center text-sm text-slate-500">Nenhum casal cadastrado.</p>}</div></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-900">Equipes de trabalho</h2><p className="mt-1 text-sm text-slate-500">Voluntários existentes assumem funções em cada edição.</p><div className="mt-4 grid gap-2">{dados.equipe.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 px-4 py-3"><div><strong className="text-sm text-slate-900">{item.voluntarioNome}</strong><p className="text-xs text-slate-500">{item.equipe} · {item.funcao}</p></div>{item.coordenador&&<span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">Coordenação</span>}</div>)}{!dados.equipe.length&&<p className="py-6 text-center text-sm text-slate-500">A equipe ainda não foi formada.</p>}</div></section></div>
    </section>
  </main>;
}
