"use client";

import Link from "next/link";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { ClipboardPlus,ExternalLink,Search } from "lucide-react";
import toast from "react-hot-toast";
import { ProtectedArea } from "@/components/auth/ProtectedArea";
import { ModuleHeader } from "@/components/layout/ModuleHeader";
import { obterTokenAcesso } from "@/lib/auth/client-session";
import { maskTelefone } from "@/lib/formatters/masks";
import { ContaSolicitacao,SolicitacaoSecretaria,StatusSolicitacao,TipoSolicitacao } from "@/modules/secretaria/solicitacoes-types";

const tipos:Record<TipoSolicitacao,string>={BATISMO:"Batismo",CASAMENTO:"Casamento",PRIMEIRA_COMUNHAO:"Primeira Comunhão",CRISMA:"Crisma",SEGUNDA_VIA:"Segunda via de documento",INTENCAO_MISSA:"Intenção de missa",OUTROS:"Outros"};
const statuses:Record<StatusSolicitacao,string>={RECEBIDA:"Recebida",EM_ANDAMENTO:"Em andamento",AGUARDANDO_DOCUMENTOS:"Aguardando documentos",PRONTA:"Pronta",CONCLUIDA:"Concluída",CANCELADA:"Cancelada"};
const moeda=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
async function api<T>(init?:RequestInit){const token=await obterTokenAcesso();const r=await fetch("/api/secretaria/solicitacoes",{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.erro||"Operação não concluída.");return d as T;}

function Conteudo(){
  const[solicitacoes,setSolicitacoes]=useState<SolicitacaoSecretaria[]>([]);const[contas,setContas]=useState<ContaSolicitacao[]>([]);const[busca,setBusca]=useState("");const[filtro,setFiltro]=useState("ABERTAS");const[contasPagamento,setContasPagamento]=useState<Record<string,string>>({});
  const[form,setForm]=useState({tipo:"BATISMO" as TipoSolicitacao,solicitanteNome:"",telefone:"",interessadoNome:"",prazo:"",observacoes:"",valor:"0"});
  const carregar=useCallback(async()=>{try{const d=await api<{solicitacoes:SolicitacaoSecretaria[];contas:ContaSolicitacao[]}>();setSolicitacoes(d.solicitacoes);setContas(d.contas);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível carregar as solicitações.");}},[]);
  useEffect(()=>{void carregar();},[carregar]);
  const visiveis=useMemo(()=>solicitacoes.filter(s=>{const termo=busca.toLowerCase();const corresponde=!termo||`${s.protocolo} ${s.solicitanteNome} ${s.interessadoNome} ${tipos[s.tipo]}`.toLowerCase().includes(termo);const status=filtro==="TODAS"||(filtro==="ABERTAS"?!["CONCLUIDA","CANCELADA"].includes(s.status):s.status===filtro);return corresponde&&status;}),[solicitacoes,busca,filtro]);
  async function criar(e:FormEvent){e.preventDefault();try{const d=await api<{protocolo:string}>({method:"POST",body:JSON.stringify({...form,prazo:form.prazo||null,valor:Number(form.valor.replace(",","."))})});toast.success(`Solicitação ${d.protocolo} criada.`);setForm({tipo:"BATISMO",solicitanteNome:"",telefone:"",interessadoNome:"",prazo:"",observacoes:"",valor:"0"});await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível criar a solicitação.");}}
  async function alterarStatus(id:string,status:StatusSolicitacao){try{await api({method:"PATCH",body:JSON.stringify({acao:"STATUS",id,status,observacao:`Status alterado para ${statuses[status]}`})});toast.success("Status atualizado.");await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível atualizar.");}}
  async function pagar(s:SolicitacaoSecretaria){const contaId=contasPagamento[s.id]||contas[0]?.id;if(!contaId)return toast.error("Cadastre uma conta ativa na Tesouraria.");try{await api({method:"PATCH",body:JSON.stringify({acao:"PAGAR",id:s.id,contaId})});toast.success("Pagamento confirmado e lançado na Tesouraria.");await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível confirmar o pagamento.");}}
  return <main className="min-h-screen bg-slate-100"><ModuleHeader titulo="Solicitações da Secretaria"/><div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    <section className="grid gap-3 sm:grid-cols-3">{[["Solicitações abertas",solicitacoes.filter(s=>!["CONCLUIDA","CANCELADA"].includes(s.status)).length],["Aguardando documentos",solicitacoes.filter(s=>s.status==="AGUARDANDO_DOCUMENTOS").length],["Prontas para retirada",solicitacoes.filter(s=>s.status==="PRONTA").length]].map(([t,v])=><div key={String(t)} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-sm text-slate-500">{t}</p><p className="text-3xl font-black">{v}</p></div>)}</section>
    <div className="grid gap-5 lg:grid-cols-[390px_1fr]">
      <form onSubmit={criar} className="h-fit space-y-3 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ClipboardPlus className="text-blue-600"/><h2 className="text-xl font-black">Nova solicitação</h2></div><label className="block text-sm font-bold">Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value as TipoSolicitacao})} className="mt-1 min-h-12 w-full rounded-xl border bg-white px-3">{Object.entries(tipos).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="block text-sm font-bold">Nome do solicitante<input value={form.solicitanteNome} onChange={e=>setForm({...form,solicitanteNome:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-4 font-normal" required/></label><div className="grid grid-cols-2 gap-2"><label className="block text-sm font-bold">Telefone<input value={form.telefone} onChange={e=>setForm({...form,telefone:maskTelefone(e.target.value)})} inputMode="tel" maxLength={15} placeholder="(11) 99999-9999" className="mt-1 min-h-12 w-full rounded-xl border px-3 font-normal"/></label><label className="block text-sm font-bold">Prazo<input type="date" value={form.prazo} onChange={e=>setForm({...form,prazo:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-3 font-normal"/></label></div><label className="block text-sm font-bold">Nome do interessado<input value={form.interessadoNome} onChange={e=>setForm({...form,interessadoNome:e.target.value})} placeholder="Pessoa do sacramento ou documento" className="mt-1 min-h-12 w-full rounded-xl border px-4 font-normal"/></label><label className="block text-sm font-bold">Valor da taxa<input value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})} inputMode="decimal" className="mt-1 min-h-12 w-full rounded-xl border px-4 font-normal"/></label><label className="block text-sm font-bold">Observações<textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal"/></label><button className="min-h-13 w-full rounded-xl bg-blue-600 font-black text-white">Gerar protocolo</button></form>
      <section className="space-y-3"><div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={20}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar protocolo ou nome" className="min-h-11 w-full rounded-lg border pl-10 pr-3"/></div><select value={filtro} onChange={e=>setFiltro(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border bg-white px-3"><option value="ABERTAS">Solicitações abertas</option><option value="TODAS">Todas</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
        {visiveis.map(s=><article key={s.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-bold text-blue-600">{s.protocolo}</p><h3 className="font-black">{tipos[s.tipo]}</h3><p className="text-sm text-slate-600">Solicitante: {s.solicitanteNome}{s.interessadoNome&&` • Interessado: ${s.interessadoNome}`}</p></div><span className="h-fit rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{statuses[s.status]}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><p><span className="block text-xs text-slate-500">Telefone</span>{s.telefone||"Não informado"}</p><p><span className="block text-xs text-slate-500">Prazo</span>{s.prazo?new Date(`${s.prazo}T12:00:00`).toLocaleDateString("pt-BR"):"Sem prazo"}</p><p><span className="block text-xs text-slate-500">Taxa</span>{moeda(s.valor)}</p><p><span className="block text-xs text-slate-500">Pagamento</span>{s.valor===0?"Sem cobrança":s.pago?"Pago":"Pendente"}</p></div>{s.observacoes&&<p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm">{s.observacoes}</p>}<div className="mt-3 flex flex-col gap-2 sm:flex-row"><select value={s.status} onChange={e=>void alterarStatus(s.id,e.target.value as StatusSolicitacao)} className="min-h-11 flex-1 rounded-lg border bg-white px-3">{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{s.valor>0&&!s.pago&&<><select value={contasPagamento[s.id]||contas[0]?.id||""} onChange={e=>setContasPagamento({...contasPagamento,[s.id]:e.target.value})} className="min-h-11 rounded-lg border bg-white px-3"><option value="">Conta de recebimento</option>{contas.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select><button onClick={()=>void pagar(s)} className="min-h-11 rounded-lg bg-emerald-600 px-4 font-bold text-white">Confirmar pagamento</button></>}<Link href={`/secretaria/solicitacoes/${s.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 font-bold text-white"><ExternalLink size={17}/>Abrir protocolo</Link></div><p className="mt-2 text-xs text-slate-400">Registrado por {s.criadoPorNome} em {new Date(s.createdAt).toLocaleString("pt-BR")}</p></article>)}
        {!visiveis.length&&<div className="rounded-2xl bg-white p-8 text-center text-slate-500">Nenhuma solicitação encontrada.</div>}
      </section>
    </div>
  </div></main>;
}

export default function PaginaSolicitacoes(){return <ProtectedArea><Conteudo/></ProtectedArea>}
