"use client";
import { useState } from "react";
import { Database, ShieldCheck, Users } from "lucide-react";
import toast from "react-hot-toast";
import { PageHeader } from "@/components/ui/PageHeader";
import { Card } from "@/components/forms/Card";
import { auth } from "@/lib/firebase/auth";

type ResultadoAuth = { total: number; criados: number; existentes: number; perfisSincronizados: number; falhas: string[] };
async function executar(url: string) { const token = await auth.currentUser?.getIdToken(); if (!token) throw new Error("Sessão expirada."); const resposta = await fetch(url, { method: "POST", headers: { Authorization: `Bearer ${token}` } }); const dados = await resposta.json(); if (!resposta.ok) throw new Error(dados.erro); return dados; }

export default function MigracaoPage() {
  const [executando, setExecutando] = useState(false); const [resultado, setResultado] = useState<Record<string, number> | null>(null); const [executandoAuth, setExecutandoAuth] = useState(false); const [resultadoAuth, setResultadoAuth] = useState<ResultadoAuth | null>(null);
  async function migrar() { setExecutando(true); try { const dados = await executar("/api/migracao"); setResultado(dados.resultado); toast.success("Cópia para o Supabase concluída."); } catch (error) { toast.error(error instanceof Error ? error.message : "Falha na migração."); } finally { setExecutando(false); } }
  async function migrarAuth() { setExecutandoAuth(true); try { const dados = await executar("/api/migracao-auth"); setResultadoAuth(dados.resultado); toast.success(dados.sucesso ? "Usuários sincronizados com sucesso." : "Sincronização concluída com ressalvas."); } catch (error) { toast.error(error instanceof Error ? error.message : "Falha na sincronização de usuários."); } finally { setExecutandoAuth(false); } }
  return <div className="space-y-6"><PageHeader title="Migração para Supabase" description="Sincronize dados e credenciais antes do desligamento definitivo do Firebase." /><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><div className="flex gap-3"><ShieldCheck className="shrink-0" size={20} /><p>Estas operações não removem dados do Firebase. O login atual continuará funcionando até o corte definitivo.</p></div></div><div className="grid gap-6 lg:grid-cols-2"><Card title="Dados operacionais"><div className="space-y-4"><p className="text-sm text-slate-600">Atualiza no Supabase famílias, campanhas, movimentações, visitas e demais registros.</p><button onClick={() => void migrar()} disabled={executando} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-60"><Database size={18} />{executando ? "Migrando..." : "Copiar dados novamente"}</button></div></Card><Card title="Usuários e credenciais"><div className="space-y-4"><p className="text-sm text-slate-600">Cria ou atualiza as credenciais e os perfis no Supabase. Depois, cada usuário definirá a senha por recuperação de acesso.</p><button onClick={() => void migrarAuth()} disabled={executandoAuth} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white disabled:opacity-60"><Users size={18} />{executandoAuth ? "Sincronizando..." : "Sincronizar usuários"}</button></div></Card></div>{resultado && <Card title="Resultado dos dados"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(resultado).map(([tabela, total]) => <div key={tabela} className="rounded-lg bg-slate-50 p-4"><p className="text-sm text-slate-500">{tabela.replaceAll("_", " ")}</p><p className="mt-1 text-2xl font-bold">{total}</p></div>)}</div></Card>}{resultadoAuth && <Card title="Resultado dos usuários"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total", resultadoAuth.total], ["Criados", resultadoAuth.criados], ["Já existentes", resultadoAuth.existentes], ["Perfis sincronizados", resultadoAuth.perfisSincronizados]].map(([nome, total]) => <div key={String(nome)} className="rounded-lg bg-slate-50 p-4"><p className="text-sm text-slate-500">{nome}</p><p className="mt-1 text-2xl font-bold">{total}</p></div>)}</div>{resultadoAuth.falhas.length > 0 && <div className="mt-4 rounded-lg bg-red-50 p-4 text-sm text-red-800"><p className="font-semibold">Pendências:</p><ul className="mt-2 list-disc pl-5">{resultadoAuth.falhas.map((falha) => <li key={falha}>{falha}</li>)}</ul></div>}</Card>}</div>;
}
