"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { CalendarClock,Pencil,Power } from "lucide-react";
import toast from "react-hot-toast";
import { ProtectedArea } from "@/components/auth/ProtectedArea";
import { ModuleHeader } from "@/components/layout/ModuleHeader";
import { obterTokenAcesso } from "@/lib/auth/client-session";
type Horario={id:string;diaSemana:number;horario:string;descricao:string;ativo:boolean};
const dias=["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"];const vazio={id:"",diaSemana:0,horario:"",descricao:"Santa Missa",ativo:true};
async function api<T>(init?:RequestInit){const token=await obterTokenAcesso();const r=await fetch("/api/secretaria/celebracoes",{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.erro||"Operação não concluída.");return d as T;}
function Conteudo(){const[itens,setItens]=useState<Horario[]>([]);const[form,setForm]=useState(vazio);const carregar=useCallback(async()=>{try{setItens(await api<Horario[]>());}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível carregar.");}},[]);useEffect(()=>{void carregar();},[carregar]);async function salvar(e:FormEvent){e.preventDefault();try{await api({method:form.id?"PATCH":"POST",body:JSON.stringify(form.id?form:{diaSemana:form.diaSemana,horario:form.horario,descricao:form.descricao})});toast.success("Horário salvo.");setForm(vazio);await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar.");}}async function alternar(i:Horario){try{await api({method:"PATCH",body:JSON.stringify({...i,ativo:!i.ativo})});await carregar();}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível alterar.");}}return <main className="min-h-screen bg-slate-100"><ModuleHeader titulo="Agenda de celebrações"/><div className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6"><form onSubmit={salvar} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-3"><div className="flex items-center gap-2 sm:col-span-3"><CalendarClock className="text-violet-600"/><h2 className="text-xl font-black">Horário semanal</h2></div><label className="text-sm font-bold">Dia<select value={form.diaSemana} onChange={e=>setForm({...form,diaSemana:Number(e.target.value)})} className="mt-1 min-h-12 w-full rounded-xl border bg-white px-3">{dias.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label className="text-sm font-bold">Horário<input type="time" value={form.horario} onChange={e=>setForm({...form,horario:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-3" required/></label><label className="text-sm font-bold">Descrição<input value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})} className="mt-1 min-h-12 w-full rounded-xl border px-3 font-normal" required/></label><div className="flex gap-2 sm:col-span-3"><button className="min-h-12 flex-1 rounded-xl bg-violet-600 font-black text-white">Salvar horário</button>{form.id&&<button type="button" onClick={()=>setForm(vazio)} className="rounded-xl border px-5 font-bold">Cancelar</button>}</div></form><section className="grid gap-3 sm:grid-cols-2">{itens.map(i=><article key={i.id} className={`flex items-center justify-between rounded-2xl border bg-white p-4 shadow-sm ${!i.ativo?"opacity-50":""}`}><div><p className="font-black">{dias[i.diaSemana]} às {i.horario}</p><p className="text-sm text-slate-500">{i.descricao} • {i.ativo?"Ativo":"Inativo"}</p></div><div className="flex gap-2"><button onClick={()=>setForm(i)} aria-label="Editar" className="rounded-xl border p-3 text-blue-700"><Pencil size={18}/></button><button onClick={()=>void alternar(i)} aria-label={i.ativo?"Inativar":"Ativar"} className="rounded-xl border p-3"><Power size={18}/></button></div></article>)}</section></div></main>}
export default function CelebracoesPage(){return <ProtectedArea><Conteudo/></ProtectedArea>}
