import { NextRequest, NextResponse } from "next/server";
import { exigirUsuarioAtivo } from "@/lib/auth/admin-request";
import { resolverParoquiaDaRequisicao } from "@/lib/supabase/tenant";

type Contexto={params:Promise<{id:string}>};
const perfis=["admin_plataforma","admin_paroquia","atendente_secretaria","tesoureiro"];
function erro(e:unknown){const m=e instanceof Error?e.message:"Erro interno.";return NextResponse.json({erro:m},{status:m==="UNAUTHENTICATED"?401:m==="FORBIDDEN"?403:400});}

export async function GET(req:NextRequest,ctx:Contexto){try{const usuario=await exigirUsuarioAtivo(req);if(!perfis.includes(usuario.role))throw new Error("FORBIDDEN");const{supabase,paroquiaId,paroquia}=await resolverParoquiaDaRequisicao(req,usuario);const id=(await ctx.params).id;const pagamento=await supabase.from("secretaria_dizimos_pagamentos").select("id,competencia,data_pagamento,valor,forma_pagamento,observacao,status,created_at,criado_por,secretaria_dizimistas(titular_nome,conjuge_nome,cpf),tesouraria_contas(nome)").eq("id",id).eq("paroquia_id",paroquiaId).single();if(pagamento.error)throw new Error("Recebimento não encontrado.");const p=pagamento.data;const d=p.secretaria_dizimistas as unknown as {titular_nome:string;conjuge_nome:string;cpf:string}|null;const c=p.tesouraria_contas as unknown as {nome:string}|null;let responsavel="Usuário do sistema";if(p.criado_por){const perfil=await supabase.from("perfis").select("nome").eq("id",p.criado_por).maybeSingle();if(perfil.data?.nome)responsavel=perfil.data.nome;}let logoUrl:string|null=null;if(paroquia.logo_caminho){const assinatura=await supabase.storage.from("agape-documentos").createSignedUrl(paroquia.logo_caminho,3600);if(!assinatura.error)logoUrl=assinatura.data.signedUrl;}return NextResponse.json({paroquia:{nome:paroquia.nome,endereco:paroquia.endereco,logoUrl},pagamento:{id:p.id,nome:[d?.titular_nome,d?.conjuge_nome].filter(Boolean).join(" e "),cpf:d?.cpf||"",competencia:p.competencia,dataPagamento:p.data_pagamento,valor:Number(p.valor),formaPagamento:p.forma_pagamento,contaNome:c?.nome||"Conta",observacao:p.observacao,status:p.status,createdAt:p.created_at,responsavel}});}catch(e){return erro(e);}}
